:aws:  https://docs.aws.amazon.com/

= AWS Key Management Service

The filter integrates with {aws}/kms/latest/developerguide/overview.html[AWS Key Management Service].

== Establish an aliasing convention for keys within AWS KMS

The filter references KEKs within AWS via an {aws}/kms/latest/developerguide/alias-about.html[AWS key alias].

It is necessary to establish a naming convention for the alias names.  This will allow the keys used by the
filter to be kept separate from any keys used by other systems.  This document assumes that the naming convention
will be to prefix the alias used by the filter with the word `KEK_`.  If a different naming convention is used, adapt
the instructions accordingly.

== Administrator Actor

To use the filter, there must be an administrative actor established within AWS IAM.  This actor, which is likely to be a human,
has the responsibility to create keys and aliases within AWS KMS for use by the filter and permission access to them
by the Filter Actor.

The AWS permission policy {aws}/aws-managed-policy/latest/reference/AWSKeyManagementServicePowerUser.html[`AWSKeyManagementServicePowerUser`]
is a suitable model for permissions required by the Administrator Actor.

If using the CLI, these commands can be used to establish the Administrator.  This example illustrates using the user-name is `kroxylicious-admin`.
Use an alternative user-name if desired.

[source,shell]
----
aws iam create-user --user-name kroxylicious-admin
aws iam attach-user-policy --user-name kroxylicious-admin --policy-arn arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
----

== Filter Actor

To use the filter, there must be AWS identity established for the filter itself.  This actor is used exclusively by the system.  Console
access should not be given to this user.  Create an access key for the user.  The access key and secret key pair will be used by the Filter
to authenticate to AWS.

If using the CLI, these commands can be used to establish the Filter Actor.  This example illustrates using the user-name is `kroxylicious`.
Use an alternative user-name if desired.

[source,shell]
----
aws iam create-user --user-name kroxylicious
aws iam create-access-key --user-name kroxylicious
----

== Create Alias Based Policy

Create an alias based policy granting the Filter Actor permission to use keys aliased by the established naming convention.

[source,shell]
----
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
cat > /tmp/policy << EOF
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AliasBasedIAMPolicy",
			"Effect": "Allow",
			"Action": [
				"kms:Encrypt",
				"kms:Decrypt",
				"kms:GenerateDataKey*",
				"kms:DescribeKey"
			],
			"Resource": [
                "arn:aws:kms:*:${AWS_ACCOUNT_ID}:key/*"
			],
			"Condition": {
				"ForAnyValue:StringLike": {
					"kms:ResourceAliases": "alias/KEK_*"
				}
			}
		}
	]
}
EOF
aws iam create-policy --policy-name KroxyliciousRecordEncryption --policy-document file:///tmp/policy
----

== Apply Alias Based Policy to Filter Actor

[source,shell]
----
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
aws iam attach-user-policy --user-name kroxylicious --policy-arn "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/KroxyliciousRecordEncryption"
----


