:aws:  https://docs.aws.amazon.com/

= AWS Key Management Service

The filter is able to integrate with {aws}/kms/latest/developerguide/overview.html[AWS Key Management Service].

Follow the instructions below to prepare your AWS account.  You'll need a privileged AWS user
that is capable of creating users and policies to perform the set-up.

[#_establish_an_aliasing_convention_for_keys_within_aws_kms]
== Establish an aliasing convention for keys within AWS KMS

The filter references KEKs within AWS via an {aws}/kms/latest/developerguide/alias-about.html[AWS key alias].

It is necessary to establish a naming convention for the alias names. This will allow the keys used by the
filter to be kept separate from any keys used by other systems. This document assumes that the naming convention
will be to prefix the alias used by the filter with the word `KEK_`. If a different naming convention is used, adapt
the instructions accordingly.

== Administrator Actor

To use the filter, there must be an administrative identity established within AWS IAM.  This user, which is likely to be a human,
has the responsibility to manage keys and aliases within AWS KMS for use by the filter.

Use AWS IAM to create a `kroxylicious-admin` user. Attach the policies `AWSKeyManagementServicePowerUser` and `IAMUserChangePassword`
to the user. You may wish to attach policy `AWSCloudShellFullAccess` so the Administrator can use the AWS CloudShell to
use CLI to manage the KEKs. Grant the user access to the Console.

If using the CLI, the following commands can be used to establish the Administrator user.  This example illustrates using the
user-name `kroxylicious-admin`.  The choice of name is not significant.  If a different user-name is used, adapt the
instructions accordingly.

[source,shell]
----
ADMIN=kroxylicious-admin
INITIAL_PASSWORD=$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 10)
CONSOLE_URL=https://$(aws sts get-caller-identity --query Account --output text).signin.aws.amazon.com/console
aws iam create-user --user-name ${ADMIN}
aws iam attach-user-policy --user-name ${ADMIN} --policy-arn arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
aws iam attach-user-policy --user-name ${ADMIN} --policy-arn arn:aws:iam::aws:policy/IAMUserChangePassword
aws iam attach-user-policy --user-name ${ADMIN} --policy-arn arn:aws:iam::aws:policy/AWSCloudShellFullAccess
aws iam create-login-profile --user-name ${ADMIN} --password ${INITIAL_PASSWORD} --password-reset-required
echo Now log in at ${CONSOLE_URL}  with user name ${ADMIN} password ${INITIAL_PASSWORD} and change the password.
----

== Filter Actor

The Record Encryption Filter needs to be able to log in to AWS itself.  For this there needs to be service account
identity established within AWS IAM.

Use AWS IAM to create the `kroxylicious` user. Create an *Access Key* for this user. The Access Key/Secret Key pair
will be used by the Filter. Do not enable the Console for this user.

If using the CLI, these commands can be used to establish the Filter Actor.  This example illustrates using the user-name
`kroxylicious`. The choice of name is not significant.  If a different user-name is used, adapt the
instructions accordingly.

[source,shell]
----
aws iam create-user --user-name kroxylicious
aws iam create-access-key --user-name kroxylicious
----

== Create Alias Based Policy

Create an alias based policy granting permissions to use keys aliased by the established alias naming convention.

[source,shell]
----
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
cat > /tmp/policy << EOF
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AliasBasedIAMPolicy",
			"Effect": "Allow",
			"Action": [
				"kms:Encrypt",
				"kms:Decrypt",
				"kms:GenerateDataKey*",
				"kms:DescribeKey"
			],
			"Resource": [
                "arn:aws:kms:*:${AWS_ACCOUNT_ID}:key/*"
			],
			"Condition": {
				"ForAnyValue:StringLike": {
					"kms:ResourceAliases": "alias/KEK_*"
				}
			}
		}
	]
}
EOF
aws iam create-policy --policy-name KroxyliciousRecordEncryption --policy-document file:///tmp/policy
----

== Apply Alias Based Policy to Filter Actor

Attach the alias policy to the Filter Actor user.  This will allow the Filter actor to invoke the
necessary key operations on all KEKs with aliases of the prescribed form.

[source,shell]
----
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
aws iam attach-user-policy --user-name kroxylicious --policy-arn "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/KroxyliciousRecordEncryption"
----
