#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec: {}
