<#--

    Copyright Kroxylicious Authors.

    Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0

-->
<#assign filteredEntityTypes = createEntityTypeSet("GROUP_ID", "TRANSACTIONAL_ID")>
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ${outputPackage};

import java.util.EnumMap;
import java.util.Map;
import java.util.function.Predicate;

import javax.annotation.processing.Generated;

import io.kroxylicious.filter.entityisolation.EntityIsolation.EntityType;

<#list inputSpecs>
    <#items as apiSpec>
        <#if !apiSpec.hasAtLeastOneEntityField(filteredEntityTypes) && !apiSpec.hasResourceList>
import org.apache.kafka.common.message.${apiSpec.response.dataClassName};
import org.apache.kafka.common.message.${apiSpec.request.dataClassName};
        </#if>
    </#items>
</#list>

import org.apache.kafka.common.protocol.ApiKeys;
import org.apache.kafka.common.protocol.ApiMessage;

/**
* Entity isolation processor map factory.
*/
@Generated(value = "io.kroxylicious.krpccodegen.main.KrpcGenerator", comments = "Generated by ${.template_name}")
final class EntityIsolationProcessorMapFactory  {

    private EntityIsolationProcessorMapFactory() {
        // ignored
    }

    static Map<ApiKeys, EntityIsolationProcessor<? extends ApiMessage, ? extends ApiMessage, ?>> createProcessorMap(Predicate<EntityType> shouldMap, EntityNameMapper entityNameMapper) {
        var map = new EnumMap<ApiKeys, EntityIsolationProcessor<? extends ApiMessage, ? extends ApiMessage, ?>>(ApiKeys.class);

<#list inputSpecs>
    <#items as apiSpec>
        <#if apiSpec.hasAtLeastOneEntityField(filteredEntityTypes) || apiSpec.hasResourceList>
        map.put(ApiKeys.${apiSpec.apiKey}, new ${apiSpec.name}EntityIsolationProcessor(shouldMap, entityNameMapper));
        <#else>
        map.put(ApiKeys.${apiSpec.apiKey}, new PassthroughEntityIsolationProcessor<${apiSpec.request.dataClassName}, ${apiSpec.response.dataClassName}>((short) ${apiSpec.request.validVersions.lowest}, (short) ${apiSpec.request.validVersions.highest}));
        </#if>
    </#items>
</#list>
        return map;
    }
}
