:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-azure-key-vault.adoc

[id='con-azure-key-vault-key-creation-{context}']
= Creating Azure Key Vault keys

[role="_abstract"]
As a user with the *Key Vault Crypto Officer* role (or otherwise sufficient RBAC permissions to manage keys in Azure Key Vault), use either the Azure CLI or Azure PowerShell to create a *key* with *wrapKey* and *unwrapKey* operations enabled.

== Establish the naming convention for keys within key vault hierarchy

Establish a naming convention for keys to keep the filter’s keys separate from those used by other systems.

== Supported Key Types

NOTE: The key types available to you in Azure Key Vault will depend on your Azure Key Vault service tier. See the _About keys_ page in the Azure Key Vault docs for more details.

The filter accepts the following key types and their associated wrapping algorithms:

* *Symmetric Keys (`oct` or `oct-HSM`):* Uses the quantum-resistant `A256GCM` (256-bit AES GCM) wrapping algorithm, which requires a Managed HSM subscription.
* *Asymmetric Keys (`RSA` or `RSA-HSM`):* Uses the `RSA-OAEP-256` (RSAES-OAEP with SHA-256 hash and MGF1/SHA-256 mask) wrapping algorithm, which is not quantum-resistant. This wrapping algorithm does not require a Managed HSM subscription to use (however, `RSA-HSM` is not available without a premium Azure Key Vault subscription).

If you use the Azure CLI, you can create a key with a command similar to the following:

[source,shell]
----
KEY_VAULT_NAME="kroxylicious-key-vault"
KEY_NAME="KEK-<name>"
KEY_TYPE="rsa"
az keyvault key create --vault-name ${KEY_VAULT_NAME} --name ${KEY_NAME} --kty ${KEY_TYPE} --ops wrapKey unwrapKey
----
* Change `KEY_TYPE` if you want to use a key type other than RSA.
* The `wrapKey` and `unwrapKey` operations must be enabled.

When the key is created, it is recommended to use a key rotation policy.

To configure a key rotation policy with the Azure CLI, save your policy to a JSON file. An example JSON file can be found in the Azure CLI docs.

When you've prepared your policy, apply it with a command like this:

[source,shell]
----
az keyvault key rotation-policy update --vault-name ${VAULT_NAME} --name ${KEY_NAME} --value path/to/my_policy.json
----
