////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: SNIPPET

// file included in the following:
//
// con-aws-kms-plugin-configuration.adoc


.Configuration for authenticating with EC2 metadata
[source, yaml]
----
kms: AwsKmsService
kmsConfig:
  endpointUrl: https://kms.<region>.amazonaws.com
  ec2MetadataCredentials:
    iamRole: <name_of_IAM_role>
    metadataEndpoint: <EC2_metadata_endpoint>
    credentialLifetimeFactor: 0.8
  region: <region>
----
where:

* `kms` specifies the name of the KMS provider. Use `AwsKmsService`.
* `kmsConfig` specifies the configuration of the KMS service.
** `endpointUrl` AWS KMS endpoint URL, which must include the `https://` scheme.
** `ec2MetadataCredentials` configures the KMS to authenticate using EC2 metadata.
*** `iamRole` specifies the name of the IAM role associated with the EC2 instances hosting Kroxylicious.
*** `metadataEndpoint` (Optional) specifies the metadata endpoint used to obtain EC2 metadata. Defaults to `\http://169.254.169.254/`. If using IPv6, use `http://[fd00:ec2::254]` instead.
*** `credentialLifetimeFactor` (Optional) defines the factor used to determine when to refresh a credential before it expires. Defaults to `0.8`, which means the credential is refreshed once it reaches 80% of its lifetime.
** `region` defines the AWS region identifier where KMS resources are located, such as `us-east-1`. This must match the region of the KMS endpoint you're using.
