# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      - "dependencies"
      - "dev/github_actions"
  # from the docs: For GitHub Actions, use the value /. Dependabot will search the /.github/workflows directory, as well as the action.yml/action.yaml file from the root directory.
  # we need custom configuration to scan the other directories that contain action.yaml files
  - package-ecosystem: "github-actions"
    # directories supports globbing
    directories: 
      - "/.github/actions/common/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dev/github_actions"
