#!/bin/sh
#
# prepare-commit-msg hook for Kroxylicious
#
# Automatically adds DCO Signed-off-by trailer to commit messages.
#
# To install: cp scripts/git-hooks/prepare-commit-msg .git/hooks/prepare-commit-msg
#             chmod +x .git/hooks/prepare-commit-msg

NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
