// file included in the following:
//
// kroxylicious-operator/index.adoc

[id='assembly-prometheus-metrics-proxy-{context}']
= Overview of Proxy Metrics

[role="_abstract"]

The proxy provides *connections metrics* and *message metrics*.

Connection metrics allow the connections made from the clients to the proxy (the downstream) and the connection made by the proxy to the kafka cluster (the upstream) to be understood.

Message metrics allow the number of {kafka-protocol}#protocol_messages[Kafka protocol request and response messages] that flow through the proxy to be understood.

== Connection Metrics

The connection metrics count the TCP connections made from the client to the proxy (`kroxylicious_client_to_proxy_request_total`) and from the proxy to the broker (`kroxylicious_proxy_to_server_connections_total`).
These metrics count connection _attempts_, so the connection count is incremented even if the connection attempt ultimately fails.

In addition to the count metrics there are error metrics.
If an error occurs whilst the proxy is accepting a connection from the client the `kroxylicious_client_to_proxy_errors_total` is incremented by one.
If an error occurs whilst the proxy is attempting a connection to a broker the `kroxylicious_proxy_to_server_errors_total` is incremented by one.

Connection and connection error metrics are discriminated by the virtual cluster's name (`virtual_cluster`) and the broker's node ID (`node_id`).
When the client connects to the boostrap endpoint of the virtual cluster, a node ID value of `bootstrap` is recorded.

If a connection error occurs at the client, before the virtual cluster has been identified, the error `kroxylicious_client_to_proxy_errors_total` with the  virtual cluster and node ID labels set to the empty string`""`.

NOTE: Error communicated from broker to client within the Kafka protocol (such as `RESOURCE_NOT_FOUND`, `UNKNOWN_TOPIC_ID`, etc.) are not classed as errors by these counters.

|===
|Metric Name |Type |Labels|Description

|`kroxylicious_client_to_proxy_connection_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is accepted from a downstream client by the proxy. +
 This metric counts all connection attempts that reach the proxy, even those that end in error.

|`kroxylicious_client_to_proxy_errors_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is closed due to any downstream error.

|`kroxylicious_proxy_to_server_connections_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is made upstream to the server from the proxy. +
 This metric counts all connections attempted to the broker, even those that end in error.

|`kroxylicious_proxy_to_server_errors_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is closed due to any upstream error.
|===

== Message Metrics

The message metrics count the Kafka protocol requests and responses that flow through the proxy.
Request messages are counted as they flow in from client and as they flow out to the broker.
On the return path, response messages are counted as they flow in from the broker and as they

Messages metrics are discriminated by the virtual cluster's name (`virtual_cluster`), the broker's node ID (`node_id`),
the API key (`api_key`) which is the type of the message, the API key version (`api_version`) and a flag indicating
whether the Proxy needed to decode the message or not (`decoded`).

When the client connects to the boostrap endpoint of the virtual cluster, metrics are recorded with a node ID value of `bootstrap`.

NOTE: There are several situations where the metric value recorded at the client end will exceed the value recorded at the broker end.
This occurs when a filter chooses to send a short-circuit response, or chooses to close the connection. It
can also occur in some error situations where connectivity to the upstream cluster is lost.

|===
|Metric Name |Type |Labels|Description

|`kroxylicious_client_to_proxy_request_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a request arrives at the proxy from a downstream (client).

|`kroxylicious_proxy_to_server_request_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a request  goes from the proxy to an upstream (server).

|`kroxylicious_server_to_proxy_response_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a response (#1) arrives at the proxy an upstream (server).

|`kroxylicious_proxy_to_client_response_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a response goes from the proxy to a downstream (client).

|===
