[allowlist]
  description = "Global Allowlist"

  paths = [
    # Test key material
    '''kroxylicious-runtime\/src\/test\/resources\/io\/kroxylicious\/proxy\/config\/tls\/.*$''',
    '''kroxylicious-operator\/src\/test\/java\/io\/kroxylicious\/kubernetes\/operator\/TestKeyMaterial\.java$''',
    '''kroxylicious-kms-providers\/kroxylicious-kms-provider-azure-key-vault-kms-test-support\/src\/main\/java\/io\/kroxylicious\/kms\/provider\/azure\/kms\/AzureKeyVaultKmsTestKmsFacade\.java$''',
    '''kroxylicious-kms-providers\/kroxylicious-kms-provider-azure-key-vault-kms\/src\/test\/java\/io\/kroxylicious\/kms\/provider\/azure\/auth\/OauthClientCredentialsTokenServiceTest\.java$''',
  ]

