// file included in the following:
//
// assembly-aws-kms.adoc

[id='con-aws-kms-setup-{context}']
= Establish an aliasing convention for keys within AWS KMS

The filter references KEKs within AWS via an {aws}/kms/latest/developerguide/alias-about.html[AWS key alias].

It is necessary to establish a naming convention for the alias names. This will allow the keys used by the
filter to be kept separate from any keys used by other systems. This document assumes that the naming convention
will be to prefix the alias used by the filter with the word `KEK_`. If a different naming convention is used, adapt
the instructions accordingly.

== Role of the Administrator

In order to use the filter, there must be an *Administrator*.  The Administrator has the responsibility
to create encryption keys within AWS KMS which will be used to encrypt the records. It is up to the organization
deploying Record Encryption to decide how the role of the *Administrator* maps into their organization structure.

The *Administrator* must have permissions to log in to AWS and create keys in AWS KMS.  As a starting point, the
built-in AWS policy `AWSKeyManagementServicePowerUser` confers sufficient key management privileges.

To help get you started, the following commands can be used to establish an Administrator user with permissions
suitable for managing encryption keys in KMS via an AWS Cloud Shell. This example illustrates using the user-name
`kroxylicious-admin` but the choice of name is not significant.  If a different user-name is used, adapt the
instructions accordingly.

[source,shell]
----
ADMIN=kroxylicious-admin
INITIAL_PASSWORD=$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 10)
CONSOLE_URL=https://$(aws sts get-caller-identity --query Account --output text).signin.aws.amazon.com/console
aws iam create-user --user-name ${ADMIN}
aws iam attach-user-policy --user-name ${ADMIN} --policy-arn arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
aws iam attach-user-policy --user-name ${ADMIN} --policy-arn arn:aws:iam::aws:policy/IAMUserChangePassword
aws iam attach-user-policy --user-name ${ADMIN} --policy-arn arn:aws:iam::aws:policy/AWSCloudShellFullAccess
aws iam create-login-profile --user-name ${ADMIN} --password ${INITIAL_PASSWORD} --password-reset-required
echo Now log in at ${CONSOLE_URL}  with user name ${ADMIN} password ${INITIAL_PASSWORD} and change the password.
----

== Filter IAM Identity

The filter needs to be able to authenticate to AWS in order to perform the operations needed for Envelope Encryption
(generating and decrypting DEKs).  To this end, there must be an AWS IAM identity established for the filter itself with
sufficient permissions.

Use AWS IAM to create the `kroxylicious` user. Create an *Access Key* for this user. The Access Key/Secret Key pair
will be used by the Filter. Do not enable the Console for this user.

If using the CLI, these commands can be used to establish the Filter IAM Identity.  This example illustrates using the
user-name `kroxylicious`. The choice of name is not significant.  If a different user-name is used, adapt the
instructions accordingly.

[source,shell]
----
aws iam create-user --user-name kroxylicious
aws iam create-access-key --user-name kroxylicious
----

== Create Alias Based Policy

Create an alias based policy granting permissions to use keys aliased by the established alias naming convention.

[source,shell]
----
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
cat > /tmp/policy << EOF
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AliasBasedIAMPolicy",
			"Effect": "Allow",
			"Action": [
				"kms:Encrypt",
				"kms:Decrypt",
				"kms:GenerateDataKey*",
				"kms:DescribeKey"
			],
			"Resource": [
                "arn:aws:kms:*:${AWS_ACCOUNT_ID}:key/*"
			],
			"Condition": {
				"ForAnyValue:StringLike": {
					"kms:ResourceAliases": "alias/KEK_*"
				}
			}
		}
	]
}
EOF
aws iam create-policy --policy-name KroxyliciousRecordEncryption --policy-document file:///tmp/policy
----

== Apply Alias Based Policy to Filter IAM Identity

Attach the alias policy to the Filter IAM Identity.  This will allow the Filter to invoke the
necessary key operations on all KEKs with aliases of the prescribed form.

[source,shell]
----
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
aws iam attach-user-policy --user-name kroxylicious --policy-arn "arn:aws:iam::${AWS_ACCOUNT_ID}:policy/KroxyliciousRecordEncryption"
----
