#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      demo:
        targetCluster:
          bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        clusterNetworkAddressConfigProvider:
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: localhost:9292
            brokerAddressPattern: kroxylicious-service
        logNetwork: false
        logFrames: false
