#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

# Note the v1 in the filename refers to the version of the CustomResourceDefinition
# not any of the versions of API being defined.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: kafkaprotocolfilters.filter.kroxylicious.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: filter.kroxylicious.io
  scope: Namespaced
  names:
    categories:
      - kroxylicious-plugins
    plural: kafkaprotocolfilters
    singular: kafkaprotocolfilter
    kind: KafkaProtocolFilter
    shortNames:
      - kpf
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 63
                  pattern: "[a-z0-9]([a-z0-9-]*[a-z0-9])?"
            spec:
              type: object
              properties:
                type:
                  description: The Java class name of the filter implementation.
                  type: string
                config:
                  description: The filter's configuration.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                observedGeneration:
                  description: |
                    The metadata.generation that was observed during the last reconciliation by the operator.
                  type: integer