#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

# Note the v1 in the filename refers to the version of the CustomResourceDefinition
# not any of the versions of API being defined.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: kafkaprotocolfilters.filter.kroxylicious.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: filter.kroxylicious.io
  scope: Namespaced
  names:
    plural: kafkaprotocolfilters
    singular: kafkaprotocolfilter
    kind: KafkaProtocolFilter
    shortNames:
      - kpf
    categories:
      - kroxylicious
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: ResolvedRefs
          description: Whether the other resources referenced by this protocol filter can be found.
          jsonPath: ".status.conditions[?(@.type==\"ResolvedRefs\")].status"
          type: string
          priority: 0
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 63
                  pattern: "[a-z0-9]([a-z0-9-]*[a-z0-9])?"
            spec:
              type: object
              required:
                - type
                - configTemplate
              properties:
                type:
                  description: The Java class name of the filter implementation.
                  type: string
                configTemplate:
                  description: The filter's configuration, subject to config provider interpolation.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                observedGeneration:
                  description: |
                    The metadata.generation that was observed during the last reconciliation by the operator.
                  type: integer
                conditions:
                  # Mapped to Java type io.kroxylicious.kubernetes.api.common.Condition
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        description: |
                          lastTransitionTime is the last time the condition transitioned from one status to another. 
                          This should be when the underlying condition changed. 
                          If that is not known, then using the time when the API field changed is acceptable.
                        type: string
                        format: date-time
                      message:
                        description: |
                          message is a human readable message indicating details about the transition. 
                          This may be an empty string.
                        type: string
                        default: ""
                        nullable: false
                      observedGeneration:
                        description: |
                          observedGeneration represents the .metadata.generation that the condition was set based upon. 
                          For instance, if .metadata.generation is currently 12, but the 
                          .status.conditions[x].observedGeneration is 9, the condition is out of date with 
                          respect to the current state of the instance.
                        type: integer
                        nullable: false
                      reason:
                        description: |
                          reason contains a programmatic identifier indicating the reason for the condition's last transition. 
                          Producers of specific condition types may define expected values and meanings for this field, 
                          and whether the values are considered a guaranteed API. 
                          The value should be a CamelCase string. 
                          This field may not be empty.
                        type: string
                        nullable: false
                      status:
                        description: status of the condition, one of True, False, Unknown.
                        type: string
                        enum: [ "True", "False", "Unknown" ]
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        type: string
                    required:
                      - lastTransitionTime
                      - observedGeneration
                      - reason
                      - message
                      - type
