#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

# Note the v1 in the filename refers to the version of the CustomResourceDefinition
# not any of the versions of API being defined.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: kafkaproxyingresses.kroxylicious.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kroxylicious.io
  scope: Namespaced
  names:
    plural: kafkaproxyingresses
    singular: kafkaproxyingress
    kind: KafkaProxyIngress
    shortNames:
      - kpi
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
            spec:
              type: object
              required: ["proxyRef", "clusterIP"]
              properties:
                proxyRef:
                  type: object
                  description: "Specifies the KafkaProxy this ingress belongs to"
                  required: [ "name" ]
                  properties:
                    name:
                      description: Name is the name of the referent.
                      maxLength: 253
                      minLength: 1
                      type: string
                clusterIP:
                  type: object
                  description: |-
                    clusterIP specifies that this ingress is for access within the same Kubernetes cluster using 
                    ClusterIP Kubernetes Services.
                  required: [ "protocol" ]
                  properties:
                    protocol:
                      description: "Protocol specifies the network protocol this ingress expects to receive."
                      type: string
                      enum: ["TCP"]