// file included in the following:
//
// kroxylicious-operator/index.adoc

[id='con-prometheus-metrics-proxy-{context}']
= Overview of proxy metrics

[role="_abstract"]

The proxy provides *connection metrics* and *message metrics*.

Connection metrics allow the connections made from the clients to the proxy (downstream)
and the connection made by the proxy to the Kafka cluster (upstream) to be understood.

Message metrics allow the number of {kafka-protocol}#protocol_messages[Kafka protocol request and response messages] that flow through the proxy to be understood.

== Connection metrics

Connection metrics count the TCP connections made from the client to the proxy (`kroxylicious_client_to_proxy_request_total`) and from the proxy to the broker (`kroxylicious_proxy_to_server_connections_total`).
These metrics count connection _attempts_, so the connection count is incremented even if the connection attempt ultimately fails.

In addition to the count metrics, there are error metrics.
If an error occurs whilst the proxy is accepting a connection from the client the `kroxylicious_client_to_proxy_errors_total` metric is incremented by one.
If an error occurs whilst the proxy is attempting a connection to a broker the `kroxylicious_proxy_to_server_errors_total` metric is incremented by one.

Connection and connection error metrics include the following labels: `virtual_cluster` (the virtual cluster's name) and `node_id` (the broker's node ID).
When the client connects to the boostrap endpoint of the virtual cluster, a node ID value of `bootstrap` is recorded.

The `kroxylicious_client_to_proxy_errors_total` metric also counts connection errors that occur before a virtual cluster has been identified.
For these specific errors, the `virtual_cluster` and `node_id` labels are set to an empty string ("").

NOTE: Error conditions signaled _within_ the Kafka protocol response (such as `RESOURCE_NOT_FOUND`, `UNKNOWN_TOPIC_ID`, etc.) are not classed as errors by these metrics.

|===
|Metric Name |Type |Labels|Description

|`kroxylicious_client_to_proxy_connection_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is accepted from a client by the proxy. +
 This metric counts all connection attempts that reach the proxy, even those that end in error.

|`kroxylicious_client_to_proxy_errors_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is closed due to any downstream error.

|`kroxylicious_proxy_to_server_connections_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is made to the server from the proxy. +
 This metric counts all connections attempted to the broker, even those that end in error.

|`kroxylicious_proxy_to_server_errors_total`
|Counter
|`virtual_cluster`, `node_id`
|Incremented by one every time a connection is closed due to any upstream error.
|===

== Message metrics

Message metrics count the Kafka protocol requests and responses that flow through the proxy.

* Client-end counters
** `kroxylicious_client_to_proxy_request_total` counts requests as they arrive from the client.
** `kroxylicious_proxy_to_client_response_total` counts responses as they are returned to the client.

* Broker-end counters
** `kroxylicious_proxy_to_server_request_total` counts requests as they go to the broker.
** `kroxylicious_proxy_to_server_response_total` counts responses as they are returned by the broker.

Message metrics include the following labels: `virtual_cluster` (the virtual cluster's name), `node_id` (the broker's node ID), `api_key` (the message type), `api_version`, and `decoded` (a flag indicating if the message was decoded by the proxy).

When the client connects to the boostrap endpoint of the virtual cluster, metrics are recorded with a node ID value of `bootstrap`.

NOTE: Client-end counters (`kroxylicious_client_to_proxy_&#42;_total`) can exceed broker-end counters (`kroxylicious_proxy_to_server_&#42;_total`) when a filter sends a short-circuit response, closes the connection, or when upstream cluster connectivity is lost during message transit.

|===
|Metric Name |Type |Labels|Description

|`kroxylicious_client_to_proxy_request_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a request arrives at the proxy from a client.

|`kroxylicious_proxy_to_server_request_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a request goes from the proxy to a server.

|`kroxylicious_server_to_proxy_response_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a response arrives at the proxy from a server.

|`kroxylicious_proxy_to_client_response_total`
|Counter
|`virtual_cluster`, `node_id`, `api_key`, `api_version`, `decoded`
|Incremented by one every time a response goes from the proxy to a client.

|===
