// file included in the following:
//
// con-operator-setting-log-levels.adoc

[id='proc-operator-setting-log-levels-proxy{context}']

= Overriding proxy logging levels

[role="_abstract"]
This procedure describes how to override the logging level of the proxy.

.Prerequisites

* An instance of Kroxylicious deployed by the operator.

.Procedure

. Apply either the `KROXYLICIOUS_APP_LOG_LEVEL` or `KROXYLICIOUS_ROOT_LOG_LEVEL` environment variable to the proxy's Kubernetes Deployment.
(The Deployment resource has the same name as the `KafkaProxy`).
+
[source,bash]
----
kubectl set env -n <namespace> deployment <deployment_name> KROXYLICIOUS_APP_LOG_LEVEL=DEBUG
----

. Kubernetes will roll the proxy pods.
. Verify that the new logging level has taken affect.
+
[source,bash]
----
kubectl logs -f -n <namespace> deployment/<deployment_name>
----

== Reverting proxy logging levels

This procedure describes how to revert the logging level of the proxy back to its defaults.

.Prerequisites

* An instance of Kroxylicious deployed by the operator.

.Procedure

. Remove either the `KROXYLICIOUS_APP_LOG_LEVEL` or `KROXYLICIOUS_ROOT_LOG_LEVEL` environment variable from the proxy's Kubernetes Deployment.
+
[source,bash]
----
kubectl set env -n <namespace> deployment <deployment_name> KROXYLICIOUS_APP_LOG_LEVEL-
----
. Kubernetes will roll proxy pods.
. Verify that the logging level has reverted to its default.
+
[source,bash]
----
kubectl logs -f -n <namespace> deployment/<deployment_name>
----
