// file included in the following:
//
// assembly-proxy-monitoring.adoc

[id='proc-proxy-setting-log-levels-{context}']
= Setting log levels

[role="_abstract"]

You can independently control the logging level of both the Kroxylicious Operator and the Kroxylicious Proxy.

In both cases, logging levels are controlled using two environment variables:

* `KROXYLICIOUS_APP_LOG_LEVEL` controls the logging of the application (`io.kroxylicious` loggers). It defaults to `INFO`.
* `KROXYLICIOUS_ROOT_LOG_LEVEL` controls the logging level at the root. It defaults to `WARN`.

When trying to diagnose a problem, start first by raising the logging level of `KROXYLICIOUS_APP_LOG_LEVEL`.
If more detailed diagnostics are required, try raising the `KROXYLICIOUS_ROOT_LOG_LEVEL`. Both the proxy and operator
use Apache Log4J2 and use logging levels understood by it: `TRACE`, `DEBUG`, `INFO`, `WARN`, and `ERROR`.

WARNING: Running either the operator or the proxy at elevated logging levels can generate significant amount of logs, which may consume significant storage.
Minimize the length of time the system is run in this state.

== Overriding proxy logging levels

Apply the environment variable to the proxy's Kubernetes `Deployment` resource to override its logging level.
The `Deployment` resource has the same name as the `KafkaProxy`.

[source,bash]
----
kubectl set env -n <namespace> deployment <deployment_name> KROXYLICIOUS_APP_LOG_LEVEL=DEBUG
----

After the pods have rolled, confirm the new logging level has taken effect by tailing the log:

[source,bash]
----
kubectl logs -f -n <namespace> deployment/<deployment_name>
----

To revert the log level back to default settings:

[source,bash]
----
kubectl set env -n <namespace> deployment <deployment_name> KROXYLICIOUS_APP_LOG_LEVEL-
----

== Overriding operator logging levels

To override the logging level of the Operator, the procedure differs depending on how the operator was installed.

ifdef::include-olm[]
=== Operator Lifecycle Manager (OLM)

If you have deployed the operator using OLM, update the logging level by patching the `Subscription` resource.

Identify the name of the subscription:

[source,bash]
----
kubectl get subscriptions.operators.coreos.com --all-namespaces | grep kroxylicious
----

Patch the `Subscription` resource:

[source,bash]
----
kubectl patch subscription <subscription_name> -p '{"spec":{"config":{"env":[{"name":"KROXYLICIOUS_APP_LOG_LEVEL","value":"DEBUG"}]}}}' --type=merge
----

To revert the logging level back to its default:

[source,bash]
----
kubectl patch subscription <subscription_name> -p '{"spec":{"config":{"env":[]}}}' --type=merge
----

endif::[]

=== YAML bundle

If you have deployed the operator from a YAML bundle, apply the environment variable to the Kubernetes `Deployment` that corresponds to the operator.

[source,bash]
----
kubectl set env -n <namespace> deployment <deployment_name> KROXYLICIOUS_APP_LOG_LEVEL=DEBUG
----

To revert the log level back to default settings:

[source,bash]
----
kubectl set env -n <namespace> deployment <deployment_name> KROXYLICIOUS_APP_LOG_LEVEL-
----
