// file included in the following:
//
// con-operator-setting-log-levels.adoc

[id='proc-operator-setting-log-levels-operator-bundle-{context}']

= Overriding the operator logging level (operator installed by bundle)

[role="_abstract"]
This procedure describes how to override the logging level of the Kroxylicious Operator.
It applies when the operator was installed from the YAML bundle.

.Prerequisites

* Kroxylicious Operator installed from the YAML bundle.

.Procedure

. Apply the `KROXYLICIOUS_APP_LOG_LEVEL` or `KROXYLICIOUS_ROOT_LOG_LEVEL` environment variable to the operator's Kubernetes Deployment:
+
[source,bash]
----
kubectl set env -n kroxylicious-operator deployment kroxylicious-operator KROXYLICIOUS_APP_LOG_LEVEL=DEBUG
----
+
Kubernetes recreates the operator pod automatically.

. Verify that the new logging level has taken affect:
+
[source,bash]
----
kubectl logs -f -n kroxylicious-operator deployment/kroxylicious-operator
----

== Reverting operator logging levels

This procedure describes how to revert the logging level of the Kroxylicious Operator back to its defaults.

.Prerequisites

* Kroxylicious Operator installed from the YAML bundle.

.Procedure

. Remove the `KROXYLICIOUS_APP_LOG_LEVEL` or `KROXYLICIOUS_ROOT_LOG_LEVEL` environment variable from the proxy's Kubernetes Deployment:
+
[source,bash]
----
kubectl set env -n kroxylicious-operator deployment kroxylicious-operator KROXYLICIOUS_APP_LOG_LEVEL-
----
+
Kubernetes recreates the operator pod automatically

. Verify that the logging level has reverted to its default:
+
[source,bash]
----
kubectl logs -f -n kroxylicious-operator deployment/kroxylicious-operator
----
