:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the Entity Isolation filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for entity isolation:

.Example `filterDefinitions` configuration
[source, yaml]
----
filterDefinitions:
  - name: my-entity-isolation
    type: EntityIsolation
    config:
      entityTypes:
        - GROUP_ID
        - TRANSACTIONAL_ID
      mapper: PrincipalEntityNameMapperService
      mapperConfig:
        separator: "-"
        principalType: <principal implementation>
----
* `entityTypes` is an array of entity types to isolate. Allowed values are `GROUP_ID` and `TRANSACTIONAL_ID`.
* `mapper` is the name of the naming mapping service implementation.  Currently, this must be `PrincipalEntityNameMapperService`.
* `separator` is the string that the mapper uses to separate the principal from the resource name.
* `principalType` identifies the principal type within the subject that will be used to form the cluster-visible entity names.
Use the fully-qualified class name of the principal. Defaults to `io.kroxylicious.proxy.authentication.User` if not specified.


Refer to the {ProxyGuide} for more information about configuring the proxy.
