:experimental:
include::_assets/attributes.adoc[]

:context: record-encryption-quickstart
:quickstart: record-encryption

[id="quickstart-{context}"]
= Record Encryption Quickstart

[role="_abstract"]

You want an encryption-at-rest solution for data stored in your Apache Kafka?
This quickstart guide will show you how to do that on Kubernetes ... from scratch ... without external dependencies.
You'll be encrypting in a snap!

== Objectives

* Deploy a Kafka Cluster to a Kubernetes cluster.
* Deploy a Key Management Service (KMS) - we'll show you how, with either HashiCorp Vault or AWS Localstack.
* Deploy Kroxylicious and configure it to proxy the cluster and apply Record Encryption.
* Produce/consume records to Kafka via the proxy demonstrating the transparent encryption.
* Verify that the records are encrypted on the broker.

WARNING: You *really don't* want to use this quickstart to deploy an environment that will be used in *production*.
The quickstart deliberately keeps things quick and simple... there's no authentication, no TLS, no redundancy... Development purposes only - please!.
Refer to the documentation for Kroxylicious, Strimzi and your KMS for production best practices.

== Before you begin

You'll need the following software installed:

* https://minikube.sigs.k8s.io/docs/start[Minikube]
* https://helm.sh/docs/intro/install/[Helm]

== Start Minikube

Let's get the Kubernetes Cluster up and running.  Minikube defaults work just fine for this quickstart.

[source,shell]
----
minikube start
----

== Install the software

=== Install a KMS

Record Encryption needs somewhere to store its encryption keys, so you need to provide a KMS.
Use Helm to install either HashiCorp Vault or AWS LocalStack.

==== HashiCorp Vault

[source,shell]
----
helm repo add --force-update hashicorp https://helm.releases.hashicorp.com
helm upgrade --install vault hashicorp/vault --namespace vault --create-namespace --version 0.30.1 --set server.dev.enabled=true,server.dev.devRootToken=myroottoken --wait
----

You also need to enable the Transit Secrets Engine in Vault.

[source,shell]
----
kubectl exec -n vault statefulsets/vault -- vault secrets enable transit
----

==== AWS Local Stack
[LocalStack](https://localstack.cloud/) is a cloud service emulator that runs in a single container on your laptop or in your CI environment. 
It's intended for developing and testing cloud & Serverless apps offline.
[source,shell]
----
helm repo add --force-update localstack-repo https://helm.localstack.cloud
helm upgrade --install localstack localstack-repo/localstack --namespace localstack --create-namespace --version 0.6.24 --set service.type=ClusterIP --wait
----

=== Install the Strimzi Operator

We are going to use Strimzi to deploy the Kafka Cluster that will be proxied.
Let's install Strimzi next:

[source,shell]
----
helm repo add --force-update strimzi https://strimzi.io/charts/
helm upgrade --install strimzi-operator strimzi/strimzi-kafka-operator --namespace kafka --create-namespace --version 0.47.0
----

=== Install the Kroxylicious Operator

First, create a temporary directory for some working files.  We use a directory called `ko-install` beneath `/tmp`, but you can use any name and location you like.

[source,shell]
----
mkdir /tmp/ko-install
cd /tmp/ko-install
----

Now let's install the Kroxylicious Operator

[source,shell]
----
curl --location https://github.com/kroxylicious/kroxylicious/releases/download/v0.13.0/kroxylicious-operator-0.13.0.zip --output kroxylicious-operator.zip
unzip kroxylicious-operator.zip
kubectl apply -f install
kubectl wait --namespace kroxylicious-operator deployment/kroxylicious-operator --for=condition=Available=True --timeout=300s
----

== Deploy the Kafka Cluster

Now we need a Kafka Cluster.
This is the Kafka Cluster that will be proxied.
We'll just use one from the Strimzi Quickstart.
It will create a cluster in the `kafka` namespace

[source,shell]
----
kubectl apply -n kafka -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/tags/0.47.0/examples/kafka/kafka-single-node.yaml
kubectl wait -n kafka kafka/my-cluster --for=condition=Ready --timeout=300s
----

We'll need the boostrap server address of the cluster later, so let's assign a variable containing it now.

[source,shell]
----
DIRECT_CLUSTER_BOOTSTRAP_SERVERS=$(kubectl get -n kafka kafka my-cluster -o=jsonpath='{.status.listeners[0].bootstrapServers}')
----


== Deploy the Proxy with Record Encryption

Next, we'll deploy a Kroxylicious proxy instance using the record encryption example included in the install zip you download above.

It will create an instance of Kroxylicious that will proxy the kafka cluster you created a above, and configure it to
apply the Record Encryption filter to encrypt as records are sent by producers and decrypt them as records get fetched by consumers.
The proxy will be created the `my-proxy` namespace

[source,shell]
----
kubectl apply -f examples/record-encryption/
----

You need to update the example to know about your chosen KMS.

If you are using Vault:

[source,shell]
----
kubectl patch -n my-proxy kafkaprotocolfilters.kroxylicious.io encryption --patch '{"spec":{"configTemplate":{"kms":"VaultKmsService","kmsConfig":{"vaultToken":{"password":"myroottoken"},"vaultTransitEngineUrl":"http://vault.vault.svc.cluster.local:8200/v1/transit"}, "selector" : "TemplateKekSelector", "selectorConfig" : {"template": "KEK_$(topicName)"}}}}' --type merge
----

If you are using LocalStack:

[source,shell]
----
kubectl patch -n my-proxy kafkaprotocolfilters.kroxylicious.io encryption --patch '{"spec":{"configTemplate":{"kms":"AwsKmsService","kmsConfig":{"longTermCredentials":{"accessKeyId":{"password":"unused"},"secretAccessKey": {"password":"unused"}},"endpointUrl":"http://localstack.localstack.svc.cluster.local:4566/", "region" : "us-east-1"}, "selector" : "TemplateKekSelector", "selectorConfig" : {"template": "KEK_$(topicName)"}}}}' --type merge
----

[source,shell]
----
kubectl wait -n my-proxy kafkaproxy/simple --for=condition=Ready=True --timeout=300s
----

Let's wait for the proxy virtual cluster to be ready for connections, and then assign a variable containing the address.
We'll use this later when to produce and consumer records through the proxy.

[source,shell]
----
kubectl wait -n my-proxy virtualkafkacluster my-cluster --for=jsonpath='{.status.ingresses[0].bootstrapServer}'
PROXIED_CLUSTER_BOOTSTRAP_SERVER=$(oc get -n my-proxy virtualkafkacluster my-cluster -o=jsonpath='{.status.ingresses[0].bootstrapServer}')
----

== Create an encryption key in the KMS

Record Encryption needs an encryption key to use when encrypting the records produced to the topic.
Let's create an encryption key in our KMS now.

The filter is configured to expect a key to exist in the KMS with the name `KEK_<topic name>`.
We are going to be using a topic called `trades` so we will create a key that can be referred to using the name `KEK_trades`.

If you are using Vault:

[source,shell]
----
kubectl exec -n vault statefulsets/vault -- vault write -f transit/keys/KEK_trades
----

If you are using LocalStack, you need to create a key and an alias to that key.

[source,shell]
----
KEY_ID=$(kubectl -n localstack exec deployments/localstack --  awslocal kms create-key --query KeyMetadata.KeyId --output text)
kubectl -n localstack exec deployments/localstack -- awslocal kms create-alias --alias-name alias/KEK_trades --target-key-id ${KEY_ID}
----

== Produce some messages

Now let's use Kafka's console producer CLI to send a few records to a topic called `trades`.
The Record Encryption filter will encrypt the records before they reach broker, but this is completely transparent to the console producer.

NOTE: You can safely ignore the warning about the UNKNOWN_TOPIC_OR_PARTITION, the topic will be created automatically.

[source,shell]
----
echo 'IBM:100\nAPPLE:99' | kubectl run -n my-proxy -qi proxy-producer --image=quay.io/strimzi/kafka:0.47.0-kafka-4.0.0 --rm=true --restart=Never -- ./bin/kafka-console-producer.sh --bootstrap-server ${PROXIED_CLUSTER_BOOTSTRAP_SERVER} --topic trades
----

== Consume the messages

Now let's use Kafka's console consumer to fetch the records.
You'll see the two records we sent above.
The Record Encryption filter will decrypt the records before they reach consumer, but this is completely transparent to the console consumer.

[source,shell]
----
kubectl run -n my-proxy -qi proxy-consumer --image=quay.io/strimzi/kafka:0.47.0-kafka-4.0.0 --rm=true --restart=Never -- ./bin/kafka-console-consumer.sh  --bootstrap-server ${PROXIED_CLUSTER_BOOTSTRAP_SERVER} --topic trades --from-beginning --timeout-ms 10000
----

== Verify that the records are encrypted on the broker

Consuming the same records we wrote is a bit underwhelming! 
And, in fact, it's what we'd expect to see with a vanilla, unproxied, Kafka cluster.
So how do we know the records really encrypted on the broker?  
Let's use the console consumer again,
but this time we'll consume straight from the Kafka cluster, bypassing the proxy.
We'll get back the records, but they'll contain ciphertext, rather than the plaintext.

[source,shell]
----
kubectl run -n kafka -qi cluster-consumer --image=quay.io/strimzi/kafka:0.47.0-kafka-4.0.0 --rm=true --restart=Never -- ./bin/kafka-console-consumer.sh  --bootstrap-server ${DIRECT_CLUSTER_BOOTSTRAP_SERVERS} --topic trades --from-beginning --timeout-ms 10000
----

= Cleaning up

To clean up, remove the proxy and the kafka cluster

[source,shell]
----
kubectl delete -f examples/record-encryption/
kubectl delete -n kafka -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/tags/0.47.0/examples/kafka/kafka-single-node.yaml
----

Remove the Kroxylicious Operator.

[source,shell]
----
kubectl delete -f install
----

Use Helm to uninstall the remaining operators:

[source,shell]
----
helm uninstall -n kafka strimzi-operator --ignore-not-found
helm uninstall -n localstack localstack --ignore-not-found
helm uninstall -n vault vault --ignore-not-found
----

= What next?

Learn more about Record Encryption by referring to the the document.
You are also welcome to come talk to us about it.  Find us in slack or start a Github Discussion.