#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# The access rules for the resources the Kroxylicious Operator consumes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kroxylicious-operator-watched
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
rules:
  - # The operator needs to know about its own CRs and be able to patch the annotations
    apiGroups:
      - "kroxylicious.io"
    resources:
      - kafkaproxies
      - virtualkafkaclusters
      - kafkaservices
      - kafkaproxyingresses
      - kafkaprotocolfilters
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - # The operator needs to update the status on its own CRs
    apiGroups:
      - "kroxylicious.io"
    resources:
      - kafkaproxies/status
      - virtualkafkaclusters/status
      - kafkaservices/status
      - kafkaproxyingresses/status
      - kafkaprotocolfilters/status
    verbs:
      - get
      - patch
      - update
  - # the operator needs get/list/watch on these because they can be referenced
    # from our CRs, so the operator needs to be able to resolve them.
    apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
