#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# The access rules for the resources the Kroxylicious Operator produces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kroxylicious-operator-dependent
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete