#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# The ServiceAccount used by the Kroxylicious Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kroxylicious-operator
  namespace: kroxylicious-operator
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator