#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# Binds the access rules for the resources the Kroxylicious Operator consumes
# to the operator's service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kroxylicious-operator-watched
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
subjects:
  - kind: ServiceAccount
    name: kroxylicious-operator
    namespace: kroxylicious-operator
roleRef:
  kind: ClusterRole
  name: kroxylicious-operator-watched
  apiGroup: rbac.authorization.k8s.io