#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# The Deployment for the operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroxylicious-operator
  namespace: kroxylicious-operator
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kroxylicious
  template:
    metadata:
      labels:
        app: kroxylicious
    spec:
      serviceAccountName: kroxylicious-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: $[io.kroxylicious.operator.image.name]
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          terminationMessagePolicy: FallbackToLogsOnError
          args: [ ]
          resources:
            requests:
              memory: 512Mi
              cpu: "1"
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /livez
