:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-kafkaprotocolfilter-resource-{context}']
= Example `KafkaProtocolFilter` resource

[role="_abstract"]
If your instance of Kroxylicious runs on Kubernetes, you must use a `KafkaProtocolFilter` resource to contain the filter configuration.

Here's a complete example of a `KafkaProtocolFilter` resource configured for SASL inspection:

[source,yaml]
----
kind: KafkaProtocolFilter
metadata:
  name: my-sasl-inspection-filter
spec:
  type: SaslInspection
  configTemplate:
    enabledMechanisms: [ "OAUTHBEARER" ]
    requireAuthentication: true
    subjectBuilder: <class name>
    subjectBuilderConfig: <object providing configuration for the subject builder>
----
where:

* `enabledMechanisms` restricts the filter to the given SASL mechanism(s).
Refer to SASL mechanism by its name given in the xref:supported-mechanisms-{context}[supported mechanisms] table.
If omitted, the SASL mechanisms `SCRAM-SHA-256`, `SCRAM-SHA-512` and `OAUTHBEARER` will be enabled by default.
*  if `requireAuthentication` is true, a successful authentication is required before the filter forwards any requests other than those strictly required to perform SASL authentication.
If false then the filter will forward all requests regardless of whether SASL authentication has been attempted or was successful. Defaults to false.
* `subjectBuilder` is the name of a plugin class implementing `io.kroxylicious.proxy.authentication.SaslSubjectBuilderService`.
If omitted, a default subject builder creates a principal with name matching the SASL authorized ID.
* `subjectBuilderConfig` provides subject builder configuration.

Refer to the {OperatorGuide} for more information about configuration on Kubernetes.
