:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for Oauth Bearer validation:

.Example `filterDefinitions` configuration
[source, yaml]
----
filterDefinitions:
  - name: my-sasl-inspection-filter
    type: SaslInspection
    config:
      enabledMechanisms: [ "OAUTHBEARER" ] # <1>
      requireAuthentication: true # <2>
----
<1> Restricts the filter to the given SASL mechanism(s).
Refer to SASL mechanism by its name given in the xref:supported-mechansisms-{context}[supported mechanisms] table.
If omitted, the SASL mechanisms `SCRAM-SHA-256`, `SCRAM-SHA-512` and `OAUTHBEARER` will be enabled by default.
<2> If true then successful authentication will be required before the filter will forward any requests other than those strictly required to perform SASL authentication.
If false then the filter will forward all requests regardless of whether SASL authentication has been attempted or was successful. Defaults to false.

Refer to the {ProxyGuide} for more information about configuring the proxy.
