:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-kafkaprotocolfilter-resource-{context}']
= Example `KafkaProtocolFilter` resource

[role="_abstract"]
If your instance of Kroxylicious runs on Kubernetes, you must use a `KafkaProcotolFilter` resource to contain the filter configuration.

Here's a complete example of a `KafkaProtocolFilter` resource configured for SASL inspection:

[source,yaml]
----
kind: KafkaProtocolFilter
metadata:
  name: my-sasl-inspection-filter
spec:
  type: SaslInspection
  configTemplate:
    enabledMechanisms: [ "OAUTHBEARER" ] # <1>
    requireAuthentication: true # <2>
    subjectBuilder: <class name> # <3>
    subjectBuilderConfig: <object providing configuration for the subject builder> # <4>
----
<1> Restricts the filter to the given SASL mechanism(s).
Refer to SASL mechanism by its name given in the xref:supported-mechansisms-{context}[supported mechanisms] table.
If omitted, the SASL mechanisms `SCRAM-SHA-256`, `SCRAM-SHA-512` and `OAUTHBEARER` will be enabled by default.
<2> If true then successful authentication will be required before the filter will forward any requests other than those strictly required to perform SASL authentication.
If false then the filter will forward all requests regardless of whether SASL authentication has been attempted or was successful. Defaults to false.
<3> The name of a plugin class implementing `io.kroxylicious.proxy.authentication.SaslSubjectBuilderService`.
If omitted, a default subject builder is used that creates a principal with name matching the SASL authorized id.
<4> Subject builder configuration.

Refer to the {OperatorGuide} for more information about configuration on Kubernetes.
