:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-kafkaprotocolfilter-resource-{context}']
= Example `KafkaProtocolFilter` resource

[role="_abstract"]
If your instance of Kroxylicious runs on Kubernetes, you must use a `KafkaProcotolFilter` resource to contain the filter configuration.

Here's a complete example of a `KafkaProtocolFilter` resource configured for Oauth Bearer validation:

.Example `KafkaProtocolFilter` resource for record validation
[source,yaml]
----
kind: KafkaProtocolFilter
metadata:
  name: my-sasl-inspection-filter
spec:
  type: SaslInspection
  configTemplate:
    enabledMechanisms: [ "OAUTHBEARER" ] # <1>
    requireAuthentication: true # <2>
----
<1> Restricts the filter to the given SASL mechanism(s).
Refer to SASL mechanism by its name given in the xref:supported-mechansisms-{context}[supported mechanisms] table.
If omitted, the SASL mechanisms `SCRAM-SHA-256`, `SCRAM-SHA-512` and `OAUTHBEARER` will be enabled by default.
<2> If true then successful authentication will be required before the filter will forward any requests other than those strictly required to perform SASL authentication.
If false then the filter will forward all requests regardless of whether SASL authentication has been attempted or was successful. Defaults to false.

Refer to the {OperatorGuide} for more information about configuration on Kubernetes.
