:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for Oauth Bearer validation:

.Example `filterDefinitions` configuration
[source, yaml]
----
filterDefinitions:
  - name: my-sasl-inspection-filter
    type: SaslInspection
    config:
      enabledMechanisms: [ "OAUTHBEARER" ] # <1>
----
<1> Restricts the filter to the given SASL mechanism(s).
Refer to SASL mechanism by its name given in the xref:supported-mechansisms-{context}[supported mechanisms] table.
If omitted, the SASL mechanisms `SCRAM-SHA-256`, `SCRAM-SHA-512` and `OAUTHBEARER` will be enabled by default.

Refer to the {ProxyGuide} for more information about configuring the proxy.
