:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-sasl-inspection-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for SASL inspection:

[source, yaml]
----
filterDefinitions:
  - name: my-sasl-inspection-filter
    type: SaslInspection
    config:
      enabledMechanisms: [ "OAUTHBEARER" ]
      requireAuthentication: true
      subjectBuilder: <class name>
      subjectBuilderConfig: <object providing configuration for the subject builder>
----
where:

* `enabledMechanisms` restricts the filter to the given SASL mechanism(s).
Refer to SASL mechanism by its name given in the xref:supported-mechanisms--{context}[supported mechanisms] table.
If omitted, the SASL mechanisms `SCRAM-SHA-256`, `SCRAM-SHA-512` and `OAUTHBEARER` will be enabled by default.
*  if `requireAuthentication` is true, a successful authentication is required before the filter forwards any requests other than those strictly required to perform SASL authentication.
If false then the filter will forward all requests regardless of whether SASL authentication has been attempted or was successful. Defaults to false.
* `subjectBuilder` is the name of a plugin class implementing `io.kroxylicious.proxy.authentication.SaslSubjectBuilderService`.
If omitted, a default subject builder creates a principal with name matching the SASL authorized ID.
* `subjectBuilderConfig` provides subject builder configuration.

Refer to the {ProxyGuide} for more information about configuring the proxy.
