
// file included in the following:
//
// con-virtualkafkafkacluster-overview.adoc

[id='proc-virtualkafkacluster-loadbalancer-dns-config-{context}']

= Configuring DNS  for load balancer ingress

[role="_abstract"]

When using the `loadBalancer` ingress type, you must ensure that both the `bootstrapAddress` and the names generated from `advertisedBrokerAddressPattern` resolve to the *external address* of the Kubernetes `Service` underlying the load balancer on the *network where the off-cluster applications run*.

.Prerequisites

* The Kroxylicious Operator is installed.
* `KafkaProxy`, `VirtualKafkaCluster`, and `KafkaProxyIngress` resources are deployed.
* The `VirtualKafkaCluster` and `KafkaProxyIngress` resources are configured to use a `loadBalancer` ingress.
* DNS can be configured on the network where the off-cluster applications run.
* Network traffic can to flow from the application network run to the external addresses provided by the Kubernetes cluster.

.Procedure

ifndef::OpenShiftOnly[]
. If using Minikube as your Kubernetes environment, enable the {Minikube}/docs/commands/tunnel/[Minikube Load Balancer tunnel] by running the following command.
  Use a separate console window to do this as the command needs to stay running for the tunnel to work.
+
[source,shell]
----
minikube tunnel
----
endif::OpenShiftOnly[]
. Run the following command to discover the *external address* being used by the load balancer:
+
[source,shell]
----
kubectl get service -n <namespace> <proxy-name>-sni -o=jsonpath='{.status.loadBalancer.ingress[0]}'
----
+
Replace `<namespace>` with the name of the Kubernetes namespace where the resources are deployed and replace `<proxy-name>` with the name of the `KafkaProxy` resource.
+
Depending on your Kubernetes environment, the command returns an IP address or a hostname.
This is the external address of the load balancer.

. Configure your DNS so that the bootstrap and broker names resolve to the external address.
+
Assuming a `bootstrapAddress` of `$(virtualClusterName).kafkaproxy.example.com`, an `advertisedBrokerAddressPattern` of `broker-$(nodeId).$(virtualClusterName).kafkaproxy.example.com`,
a Kafka cluster uses node IDs (0-2), and a virtual cluster name of `my-cluster`, the following DNS mappings are listed:
+
[source,text]
----
my-cluster.kafkaproxy.example.com => <external address>
broker-0.my-cluster.kafkaproxy.example.com => <external address>
broker-1.my-cluster.kafkaproxy.example.com => <external address>
broker-2.my-cluster.kafkaproxy.example.com => <external address>
----
+
The exact steps vary by environment and network setup.
. Confirm that the names resolve from the application network:
+
[source,shell]
----
nslookup mycluster.kafkaproxy.example.com
nslookup broker-0.mycluster.kafkaproxy.example.com
----

