[id='con-configuring-client-connections-{context}']
= Securing connections from clients

[role="_abstract"]
To secure client connections to virtual clusters, configure TLS on the virtual cluster by doing the following:

* Obtain a server certificate for the virtual cluster from a Certificate Authority (CA). +
Ensure the certificate matches the names of the virtual cluster's bootstrap and broker addresses. +
This may require wildcard certificates and Subject Alternative Names (SANs).

* Provide the TLS configuration using the `tls` properties in the virtual cluster's configuration to enable it to present the certificate to clients. 
Depending on your certificate format, apply one of the following examples.

* For mutual TLS, you may also use the `trust` properties to configure the virtual cluster to use TLS client authentication.

* If desired, you may restrict the TLS protocols and/or cipher suites that may be used to form the TLS connection.

NOTE: TLS is recommended on Kafka clients and virtual clusters for production configurations.

.Example - applying a PKCS #12 formatted server certificate to the virtual cluster
[source,yaml]
----
virtualClusters:
  my-cluster-proxy:
    tls:
      key:
        storeFile: <path>/server.p12  # <1>             
        storePassword:
          passwordFile: <path>/store.password # <2>    
        keyPassword:
          passwordFile: <path>/key.password # <3>       
        storeType: PKCS12 # <4>                            
      # ...
----
<1> PKCS #12 store containing the private-key and certificate/intermediates of the virtual cluster.
<2> Password to protect the PKCS #12 store.
<3> (Optional) Password for the key. If a password is not specified, the keystore’s password is used to decrypt the key too.
<4> (Optional) Keystore type. If a keystore type is not specified, the default JKS (Java Keystore) type is used.

.Example - applying a PEM formatted server certificate/key pair to the virtual cluster
[source,yaml]
----
virtualClusters:
  my-cluster-proxy:
    tls:
      key:
        privateKeyFile: <path>/server.key   # <1>       
        certificateFile: <path>/server.crt # <2> 
        keyPassword:
          passwordFile: <path>/key.password # <3>
# …
----
<1> Private key of the virtual cluster.
<2> Public certificate of the virtual cluster.
<3> (Optional) Password for the key.

You can configure the virtual cluster to require that clients present a certificate for authentication. 
The virtual cluster verifies that the client's certificate is signed by one of the CA certificates contained in a trust store.  
If verification fails, the client's connection is refused.

.Example - applying TLS client authentication using PKCS #12 formatted trust store
[source,yaml]
----
virtualClusters:
  demo:
    tls:
      key:
        # ...
      trust:
        storeFile: <path>/trust.p12 # <1>
        storePassword:
          passwordFile: <path>/trust.password # <2>
        storeType: PKCS12 # <3>
        trustOptions:
          clientAuth: REQUIRED # <4>
# …
----
<1> PKCS #12 store containing CA certificate(s) used to verify that the client's certificate is trusted.
<2> (Optional) Password to protect the PKCS #12 store.
<3> (Optional) Keystore type. If a keystore type is not specified, the default JKS (Java Keystore) type is used.
<4> Client authentication mode. 
If set to `REQUIRED`, the client must present a valid certificate. 
If set to `REQUESTED`, the client is requested to present a certificate. If presented, the certificate is validated. If the client chooses not to present a certificate the connection is still allowed. 
If set to `NONE`, client authentication is disabled.

NOTE: The client's identity, as established through TLS client authentication, is currently not relayed to the target cluster. 
For more information, see the {github-issues}/issues/1637[related issue].

You may restrict the TLS protocols by either specifying an allow list of TLS protocols to be enabled, or
specify a deny list of those protocols that should be disallowed from the platform's default. If you specify
both an allow and a deny list, the deny list will be applied to be the allow list. If neither an allow nor a deny
list is specified, the virtual cluster will use the defaults provided by the platform.

When the client connects, the client and the virtual cluster will negotiate the highest mutually acceptable TLS protocol.
If the two have no protocols in common, the connection will fail.

The names of the TLS protocols are defined by {java-17-specs}/security/standard-names.html#sslcontext-algorithms[Java specification].

.Example - restricting the TLS protocols using an allow list

[source,yaml]
----
virtualClusters:
  demo:
    tls:
      # ...
      protocols:
        allow:  # <1>
        - TLSv1.3
        - TLSv1.2
----
<1> List of TLS protocols to be allowed.

.Example - restricting the TLS protocols using a deny list

[source,yaml]
----
virtualClusters:
  demo:
    tls:
      # ...
      protocols:
        deny:  # <1>
        - TLSv1.1
----
<1> List of TLS protocols to be disallowed.

You may restrict the TLS cipher suite by either specifying an allow list of cipher suite to be enabled, in preference
order, or specify a deny list of those cipher suite that should be disallowed from the platform's default. If you specify
both an allow and a deny list, the deny list will be applied to be the allow list. If neither an allow nor a deny
list is specified, the virtual cluster will use the default cipher suites (and preference order) provided by the platform.

When the client connects, the client and the virtual cluster will negotiate the most preferred mutually acceptable cipher
suite. If the two have no cipher suites in common, the connection will fail.

The names of the cipher suite are defined by {java-17-specs}/security/standard-names.html#jsse-cipher-suite-names[Java specification].

.Example - restricting the cipher suite using an allow list

[source,yaml]
----
virtualClusters:
  demo:
    tls:
      # ...
      protocols:
        allowed:  # <1>
        - TLS_ECDHE_ECDSA_WITH_AES_256_CCM
        - TLS_ECDHE_ECDSA_WITH_AES_128_CCM
----
<1> List of cipher suites to be allowed, in preference order.

.Example - restricting the cipher suite using a deny list

[source,yaml]
----
virtualClusters:
  demo:
    tls:
      # ...
      protocols:
        deny:  # <1>
        - TLS_KRB5_WITH_3DES_EDE_CBC_MD5
----
<1> List of cipher suites to be disallowed.
