// file included in the following:
//
// kroxylicious-operator/assemblies/assembly-operator-deploy-a-proxy.adoc

[id='con-configuring-virtualkafkacluster-{context}']
= Virtual cluster configuration for LoadBalancer access with TLS

A `VirtualKafkaCluster` resource defines a logical Kafka cluster that is accessible to clients over the network.

The virtual cluster references the following:

* A `KafkaProxy` resource that the proxy is associated with.
* One or more `KafkaProxyIngress` resources that expose the virtual cluster to Kafka clients.
* A `KafkaService` resource that defined the backend Kafka cluster.
* Zero or more `KafkaProtocolFilter` resources that apply filters to the Kafka protocol traffic passing between clients and the backend Kafka cluster.

This example shows a `VirtualKafkaCluster`, exposing it to external Kafka clients via a LoadBalancer Service.
It uses TLS as the transport protocol (LoadBalancer ingress requires TLS).

.Example `VirtualKafkaCluster` configuration with downstream TLS
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef: # <1>
    name: simple
  targetKafkaServiceRef: # <2>
    name: my-cluster
  ingresses:
    - ingressRef: # <3>
        name: load-balancer
      tls:
        certificateRef: # <4>
          name: 'proxy-server-tls'
          kind: Secret
----
<1> The `proxyRef` names the `KafkaProxy` hosting with this virtual cluster.
  It must be in the same namespace as the `VirtualKafkaCluster`.
<2> The `KafkaService` that is proxied by the virtual cluster.
  It must be in the same namespace as the `VirtualKafkaCluster`.
<3> Ingresses to expose the virtual cluster.
  Each ingress names a `KafkaProxyIngress` which must be in the same namespace as the `VirtualKafkaCluster`.
<4> TLS server certificate that the Proxy will use to secure connections on this particular ingress. The `Secret` must be in the same namespace as the `VirtualKafkaCluster`