[id='con-configuring-kafkaservice-trust-{context}']
= Trusting the proxied cluster's TLS certificates

By default, when connecting to the proxied cluster using TLS, the proxy will use the platform's default trust store.
This will usually work if the proxied cluster's TLS certificates were issued by a well-known public Certificate Authority (CA).
It will not work if the proxied cluster's TLS certificates were issued by a private Certificate Authority.

IMPORTANT: It is good practice to configure trust explicitly, even when proxied cluster's TLS certificates are signed by a public CA.

.Example `KafkaService` configured to trust TLS certificates signed by any of the CAs in the `trusted-cas.pem` entry of the `ConfigMap` called `trusted-cas`
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    trustAnchorRef: # <1>
      kind: ConfigMap # <2>
      name: trusted-cas # <3>
      key: trusted-cas.pem # <4>
    # ...
----
<1> The `trustAnchorRef` object references a separate Kubernetes resource which contains the CA certificates to be trusted
<2> The `kind` is optional and defaults to `ConfigMap`.
<3> The `name` is the name of the resource of the given `kind`. This resource must exist in the same namespace as the `KafkaService`
<4> The `key` identifies the entry in the given resource. The corresponding value should be a PEM-encoded set of CA certificates.