[id='con-configuring-kafkaservice-cipher-{context}']
= Controlling the TLS ciphers used

Some cipher suites, which are enabled by default for interoperability purposes, are no longer consider secure.

IMPORTANT: It is considered good practice to disable insecure cipher suites. You can only do this is the proxied Kafka cluster you want to connect to supports the cipher suites that you want to use.

The cipher suites that are enabled by default can depend on the JVM used in the proxy image and the TLS protocol version which is negotiated.

.Example `KafkaService` configured so that the proxy will negotiate TLS connection using only the listed ciphers.
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    # ...
    cipherSuites: # <1>
      allowed: # <2>
       - TLS_AES_128_GCM_SHA256
       - TLS_AES_256_GCM_SHA384
----
<1> The `cipherSuites` object configures the cipher suites.
<2> `allowed` lists the cipher suites which are permitted.

The `cipherSuites` object also supports `denied` if you prefer to exclude the unpermitted cipher suites, rather than include the permitted cipher suites.

The names of the cipher suites supported depend on the JVM in the proxy container image.
See {cipherSuiteNames}.