[id='con-configuring-client-connections-{context}']
= Securing connections from clients

[role="_abstract"]
To secure client connections to virtual clusters, configure TLS on the virtual cluster by doing the following:

* Obtain a server certificate for the virtual cluster from a Certificate Authority (CA). +
Ensure the certificate matches the names of the virtual cluster's bootstrap and broker addresses. +
This may require wildcard certificates and Subject Alternative Names (SANs).

* Provide the TLS configuration using the tls properties in the virtual cluster's configuration to enable it to present the certificate to clients. 
Depending on your certificate format, apply one of the following examples.

You may also configure the virtual cluster to use TLS client authentication.

NOTE: TLS is recommended on Kafka clients and virtual clusters for production configurations.

.Example PKCS #12 configuration
[source,yaml]
----
virtualClusters:
  my-cluster-proxy:
    tls:
      key:
        storeFile: <path>/server.p12  # <1>             
        storePassword:
          passwordFile: <path>/store.password # <2>    
        keyPassword:
          passwordFile: <path>/key.password # <3>       
        storeType: PKCS12 # <4>                            
      # ...
----
<1> PKCS #12 store containing the private-key and certificate/intermediates of the virtual cluster.
<2> Password to protect the PKCS #12 store.
<3> (Optional) Password for the key. If a password is not specified, the keystore’s password is used to decrypt the key too.
<4> (Optional) Keystore type. If a keystore type is not specified, the default JKS (Java Keystore) type is used.

.Example PEM configuration
[source,yaml]
----
virtualClusters:
  my-cluster-proxy:
    tls:
      key:
        privateKeyFile: <path>/server.key   # <1>       
        certificateFile: <path>/server.crt # <2> 
        keyPassword:
          passwordFile: <path>/key.password # <3>
# …
----
<1> Private key of the virtual cluster.
<2> Public certificate of the virtual cluster.
<3> (Optional) Password for the key.

You may configure the virtual cluster to require that clients present a certificate to the virtual
cluster. The virtual cluster verifies the client's certificate is signed by one of the CA certificates
contained with a trust store.  If verification fails, the client's connection will be refused.

.Example to configure TLS client authentication using PKCS12 trust store
[source,yaml]
----
virtualClusters:
  demo:
    tls:
      key:
        # ...
      trust:
        storeFile: <path>/trust.p12 #1 <1>
        storePassword:
          passwordFile: <path>/trust.password # <2>
        storeType: PKCS12 # <3>
        trustOptions:
          clientAuth: REQUIRED # <4>
# …
----
<1> PKCS #12 store containing CA certificate(s) used to verify that the client's certificate is trusted.
<2> (Optional) Password to protect the PKCS #12 store.
<3> (Optional) Keystore type. If a keystore type is not specified, the default JKS (Java Keystore) type is used.
<4> If set to the value `REQUIRED`, the client must present a valid certificate.  If set to `REQUESTED` the client
    will be requested to present a certificate.  If a certificate is presented, it will be validated. If the client
    chooses not to present a certificate the connection is still allowed.  The value `NONE` disables client authentication.

NOTE: The client's identity established by TLS client authentication is not relayed to the target cluster. See
(https://github.com/kroxylicious/kroxylicious/issues/1637)[issue].



