// file included in the following:
//
// kroxylicious-operator/assemblies/assembly-operator-deploy-a-proxy.adoc

[id='con-virtualkafkacluster-overview-{context}']
= Virtual cluster configuration

A `VirtualKafkaCluster` resource defines a logical Kafka cluster that is accessible to clients over the network.

The virtual cluster references the following:

* A `KafkaProxy` resource that the proxy is associated with.
* One or more `KafkaProxyIngress` resources that expose the virtual cluster to Kafka clients.
  It also provides virtual cluster specific configuration to the ingress (such as TLS certificates and other parameters).
* A `KafkaService` resource that defined the backend Kafka cluster.
* Zero or more `KafkaProtocolFilter` resources that apply filters to the Kafka protocol traffic passing between clients and the backend Kafka cluster.

This example shows a `VirtualKafkaCluster`, exposing it to Kafka clients running on the same Kubernetes cluster.
It uses plain TCP (as opposed to TLS) as the transport protocol.

.Example `VirtualKafkaCluster` configuration with single `clusterIP` ingress
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef: # <1>
    name: simple
  targetKafkaServiceRef: # <2>
    name: my-cluster
  ingresses:
    - ingressRef: # <3>
        name: cluster-ip
----
<1> The `proxyRef` names the `KafkaProxy` hosting with this virtual cluster.
  It must be in the same namespace as the `VirtualKafkaCluster`.
<2> The `KafkaService` that is proxied by the virtual cluster.
  It must be in the same namespace as the `VirtualKafkaCluster`.
<3> Ingresses to expose the virtual cluster.
  Each ingress names a `KafkaProxyIngress` which must be in the same namespace as the `VirtualKafkaCluster`.

This example shows a `VirtualKafkaCluster`, exposing it to Kafka clients running both on and off-cluster, both using TLS.
As TLS is used ingress configuration must be provided, referencing a TLS server certificate.

.Example `VirtualKafkaCluster` configuration with two ingresses using TLS
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef: # <1>
    name: simple
  targetKafkaServiceRef: # <2>
    name: my-cluster
  ingresses: # <3>
    - ingressRef:
        name: cluster-ip
        certificateRef:
          name: 'cluster-ip-server-cert' # <4>
          kind: Secret
    - ingressRef:
        name: load-balancer
        certificateRef:
          name: 'external-server-cert' # <5>
          kind: Secret
----
<1> The `proxyRef` names the `KafkaProxy` hosting with this virtual cluster.
It must be in the same namespace as the `VirtualKafkaCluster`.
<2> The `KafkaService` that is proxied by the virtual cluster.
It must be in the same namespace as the `VirtualKafkaCluster`.
<3> Ingresses to expose the virtual cluster.
<4> Reference to a secret containing the server certificate for the cluster-ip ingress.
<5> Reference to a secret containing the server certificate for the load-balancer ingress.

include::./con-virtualkafkacluster-clusterip-generate-tls-certificates.adoc[leveloffset=+1]
include::./con-virtualkafkacluster-loadbalancer-generate-tls-certificates.adoc[leveloffset=+1]
include::./proc-virtualkafkacluster-loadbalancer-dns-config.adoc[leveloffset=+1]
