[id='con-configuring-kafkaservice-protocol-{context}']
= Controlling TLS versions

Some older versions of TLS (and SSL before it) are now considered insecure.

IMPORTANT: It is good practice to disable insecure protocol versions. Only do this if the proxied Kafka cluster supports the version that you want to use.

This example configures a `KafkaService` to allow only TLS v1.3 and v1.2 when connecting to `kafka.example.com`.

.Example `KafkaService` with restricted TLS protocol versions
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    # ...
    protocols: # <1>
      allowed: # <2>
        - TLSv1.3
        - TLSv1.2
----
<1> The `protocols` property configures the TLS protocol versions
<2> `allowed` lists the versions of TLS which are permitted.

The `protocols` property also supports `denied`, if you prefer to list the versions to exclude instead.

The names of the TLS procotol versions supported depend on the JVM in the proxy container image.
See {tlsProtocolNames}.