// file included in the following:
//
// con-virtualkafkafkacluster-overview.adoc

[id='con-virtualkafkacluster-clusterip-generate-tls-certificates-{context}']

= Generating TLS certificates for `clusterIP` ingress type

[role="_abstract"]

When using the `clusterIP` ingress type with the `TLS` protocol, you must provide suitable TLS certificates to secure communication.

The basic steps are as follows:

* Generate a TLS server certificate that covers the service names assigned to the virtual cluster by the ingress.
* Provide the certificate to the virtual cluster using a Kubernetes `Secret` of type `kubernetes.io/tls`.

The exact procedure for generating the certificate depends on the tooling and processes used by your organization.

The certificate must meet the following criteria:

* The certificate needs to be signed by a CA that is trusted by the *on-cluster applications* that connect to the virtual cluster.
* The format of the certificate must be PKCS#8 encoded PEM (Privacy Enhanced Mail).
  It must not be password protected.
* The certificate must use SAN (Subject Alternate Names) to list all service names or use a wildcard TLS certificate that covers them all.
Assuming a virtual cluster name of `my-cluster`, an ingress name of `cluster-ip`, and a Kafka cluster using node IDs (0-2), the following SANs must be listed in the certificate:
+
[source,text]
----
my-cluster-cluster-ip-bootstrap.<namespace>.svc.cluster.local
my-cluster-cluster-ip-0.<namespace>.svc.cluster.local
my-cluster-cluster-ip-1<namespace>.svc.cluster.local
my-cluster-cluster-ip-2<namespace>.svc.cluster.local
----

include::../../snippets/snip-create-secret-containing-pem-certificate.adoc[]
