[id='con-configuring-kafkaservice-protocol-{context}']
= Controlling TLS versions

Some older versions of TLS (and SSL before it) are now considered insecure.
They remain enabled by default in order to maximise interoperability between TLS clients and servers which only support older versions.

If the Kafka cluster than you want to connect to supports newer versions of TLS you can disable the proxy's support for older, insecure versions.
For example, if the Kafka cluster supports TLSv1.1, TLSv1.2 and TLSv1.3 you might choose to enable only TLSv1.3 support.
This would prevent a TLS downgrade attack.

IMPORTANT: It is good practice to disable insecure protocol versions.

This example configures a `KafkaService` to allow only TLS v1.3 when connecting to `kafka.example.com`.

.Example `KafkaService` with restricted TLS protocol versions.
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    # ...
    protocols: # <1>
      allowed: # <2>
        - TLSv1.3
----
<1> The `protocols` property configures the TLS protocol versions
<2> `allowed` lists the versions of TLS which are permitted.

The `protocols` property also supports `denied`, if you prefer to list the versions to exclude instead.

The names of the TLS protocol versions supported depend on the JVM in the proxy container image.
See {tlsProtocolNames}.