[id='con-configuring-kafkaservice-cipher-{context}']
= Controlling TLS cipher suites

Some cipher suites, which are enabled by default for interoperability purposes, are no longer consider secure.

IMPORTANT: It is good practice to disable insecure cipher suites. Only do this if the proxied Kafka cluster supports the cipher suites you want to allow.

The cipher suites enabled by default depend on the JVM used in the proxy image and the TLS protocol version that is negotiated.

.Example `KafkaService` configured so that the proxy will negotiate TLS connection using only the listed ciphers.
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    # ...
    cipherSuites: # <1>
      allowed: # <2>
       - TLS_AES_128_GCM_SHA256
       - TLS_AES_256_GCM_SHA384
----
<1> The `cipherSuites` object configures the cipher suites.
<2> `allowed` lists the cipher suites which are permitted.

The `cipherSuites` property also supports `denied`, if you prefer to list the cipher suites to exclude instead.

The names of the cipher suites supported depend on the JVM in the proxy container image.
See {cipherSuiteNames}.