// file included in the following:
//
// kroxylicious-operator/assemblies/assembly-operator-operate-resource-allocation.adoc

[id='con-kafkaproxy-tuning-resource-allocation-{context}']
== Configuring Proxy container CPU and memory resource limits and requests

When you define a `KafkaProxy` resource, a Kubernetes Deployment of Proxy containers is created. Each of these containers runs a single Kroxylicious Proxy process.

By default, these Proxy containers are configured with the following resource requests and limits:

- `resources.requests.cpu`: `500m`
- `resources.requests.memory`: `512Mi`
- `resources.limits.cpu`: `500m`
- `resources.limits.memory`: `512Mi`

You can learn more about Kubernetes resource management https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[here].

To replace these default resource allocations, modify the `proxyContainer` section within your `KafkaProxy` specification.

.Example `KafkaProxy` configuration with proxy container resource specification
[source,yaml]
----
kind: KafkaProxy
apiVersion: kroxylicious.io/v1alpha1
metadata:
  namespace: my-proxy
  name: simple
spec:
  infrastructure:
    proxyContainer:
      resources:
        requests:
          cpu: '400m'
          memory: '656Mi'
        limits:
          cpu: '500m'
          memory: '756Mi'
----
