[id='ref-configuring-proxy-example-{context}']
= Example Kroxylicious configuration

* Virtual clusters that represent the Kafka clusters
* Network addresses for broker communication in a Kafka cluster
* Filters to introduce additional functionality to the Kafka deployment

In this example, configuration for the Record Encryption filter is shown.

[id='con-deploying-upstream-tls-{context}']
.Example Kroxylicious configuration
[source,yaml]
----
filterDefinitions: # <1>
  - name: encryption
    type: RecordEncryption # <2>
    config: # <3>
      kms: VaultKmsService
      kmsConfig:
        vaultTransitEngineUrl: https://vault.vault.svc.cluster.local:8200/v1/transit
        vaultToken:
          passwordFile: /opt/proxy/server/token.txt
        tls: # <4>
          key:
            storeFile: /opt/cert/server.p12
            storePassword:
              passwordFile: /opt/cert/store.password
            keyPassword:
              passwordFile: /opt/cert/key.password
            storeType: PKCS12
      selector: TemplateKekSelector
      selectorConfig:
        template: "$(topicName)"
defaultFilters:
  - encryption
virtualClusters: # <5>
  my-cluster-proxy: # <6>
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093 # <7>
      tls: # <8>
        trust:
          storeFile: /opt/proxy/trust/ca.p12
          storePassword:
            passwordFile: /opt/proxy/trust/ca.password
    gateways: # <9>
    - name: mygateway
      sniHostIdentifiesNode: # <10>
        bootstrapAddress: my-cluster-proxy.kafka:9092 # <11>
        advertisedBrokerAddressPattern: broker$(nodeId).my-cluster-proxy.kafka
      tls: # <12>
        key:
          storeFile: /opt/proxy/server/key-material/keystore.p12
          storePassword:
            passwordFile: /opt/proxy/server/keystore-password/storePassword
----
<1> A list of named filter configurations.
<2> The type of filter, which is the Record Encryption filter using Vault as the KMS in this example.
<3> The configuration specific to the type of filter.
<4> If required, you can also specify the credentials for TLS authentication with the KMS, with key names under which TLS certificates are stored.
<5> Virtual cluster configuration.
<6> The name of the virtual cluster.
<7> The bootstrap address of the target physical Kafka Cluster being proxied.
<8> TLS configuration for the connection to the target cluster.
<9> The gateway of the virtual cluster defining how the virtual cluster is presented to the network.
<10> The identification scheme used to route traffic to brokers, which can be `sniHostIdentifiesNode` or `portIdentifiesNode`.
<11> The hostname and port of the bootstrap used by the Kafka clients to connect to this listener. The hostname must be resolved by the clients.
<12> TLS encryption used by the listener for securing connections with the clients.

