:experimental:
include::_assets/attributes.adoc[]

:context: authorization
:guide: authorization

[id="using-book-{context}"]
= Authorization Guide

include::_modules/authorization/con-about-{guide}-guide.adoc[leveloffset=+1]

[role="_abstract"]
The Authorization filter gives the ability to add authorization checks into a Kafka system which will be enforced by the proxy.
These authorization checks are performed in addition to any authorization checks made by the broker itself.
For an action to be allowed, both the authorization filter and broker must decide that the action is allowed.

In general, the Authorization filter will make access decisions in the same manner as Kafka itself.
This means it will apply the same authorizer checks that Kafka enforces itself and generate error responses in the same way.
Indeed, from the client's perspective, it will be impossible for it to distinguish between the proxy and kafka cluster itself.

In order to use the authorization filter, the proxy must be configured in such a way that it knows the authenticated principal.
If your applications are using TLS client authentication this may be as achieved using TODO: link to configuring subject builder
within the virtual cluster.  If your applications are authenticating using SASL, configure a TODO: link SASL Inspection Filter
to extract the authenticated principal from the client/broker SASL negotiation.

// authorization primitives
include::_modules/authorization/con-authorization-primitives.adoc[leveloffset=+1]

//configuring the authorization filter
include::_assemblies/assembly-configuring-authorization-filter.adoc[leveloffset=+1]

//trademark notices
include::_assets/trademarks.adoc[leveloffset=+1]

// glossary
include::_modules/authorization/ref-glossary.adoc[leveloffset=+1]