// file included in the following:
//
// assembly-record-encryption.adoc

[id='proc-configuring-record-encryption-filter-{context}']
= Setting up the Record Encryption filter

[role="_abstract"]
This procedure describes how to set up the Record Encryption filter.
Provide the filter configuration and the Key Encryption Key (KEK) selector to use. 
The KEK selector maps topic name to key names.  
The filter looks up the resulting key name in the KMS.

.Prerequisites

* An instance of Kroxylicious. 
For information on deploying Kroxylicious, see the link:{github}[samples and examples^].
* A config map for Kroxylicious that includes the configuration for creating virtual clusters and filters. 
* A KMS is installed and set up for the filter with KEKs to encrypt records set up for topics.

.Procedure

. Configure a `RecordEncryption` type filter.
+
.Example Record Encryption filter configuration
[source,yaml]
----
filters:
  - type: RecordEncryption
    config:
      kms:<kms_service_name> # <1>
      kmsConfig:
        <kms_specific_config> # <2>
        # ...
      selector: <KEK_selector_service_name> # <3>
      selectorConfig:
        template: "KEK_${topicName}" # <4>
	 # ...
----
<1> The KMS service name.
<2> Configuration specific to the KMS provider.
<3> The Key Encryption Key (KEK) selector to use. The `${topicName}` is a literal understood by the proxy. 
For example, if using the `TemplateKekSelector` with the template `KEK_$\{topicName}`, create a key for every topic that
is to be encrypted with the key name matching the topic name, prefixed by the string `KEK_`.
<4> The template for deriving the KEK, based on a specific topic name. 

. Verify that the encryption has been applied to the specified topics by producing messages through the proxy and then consuming directly and indirectly from the Kafka cluster.

NOTE: If the filter is unable to find the key in the KMS, the filter passes through the records belonging to that topic in the produce request without encrypting them.