#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
kind: KafkaProtocolFilter
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: transforming
  namespace: my-proxy
spec:
  type: ProduceRequestTransformation
  configTemplate:
    transformation: UpperCasing
    transformationConfig:
      charset: UTF-8
