#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
# The access rules for the resources the Kroxylicious Operator consumes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kroxylicious-operator-filter-generic
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - "filter.kroxylicious.io"
    resources:
      - kafkaprotocolfilters
    verbs:
      - get
      - list
      - watch
      # - create
      # - patch
      # - update
