:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-multi-tenancy-filter.adoc

[id='con-example-kafkaprotocolfilter-resource-{context}']
= Example `KafkaProtocolFilter` resource

[role="_abstract"]
If your instance of Kroxylicious runs on Kubernetes, you must use a `KafkaProtocolFilter` resource to contain the filter configuration.

Here's a complete example of a `KafkaProtocolFilter` resource configured for record validation:

.Example `KafkaProtocolFilter` resource for multi-tenancy
[source,yaml]
----
kind: KafkaProtocolFilter
metadata:
  name: my-multi-tenant-filter
spec:
  type: MultiTenant
  configTemplate:
    prefixResourceNameSeparator: "." # <1>
    prefixResourceName: "myprefix" # <2>
----
<1> The separator used for the prefix.
If a separator is not specified, `-` is the default.
<2> (Optional) A custom prefix for resource names.
If specified, this value is used instead of the virtual cluster name as the prefix.
If not specified, the virtual cluster name is used (default behavior).

Refer to the {OperatorGuide} for more information about configuration on Kubernetes.