////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-multi-tenancy-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for multi-tenancy:

.Example `filterDefinitions` configuration
[source, yaml]
----
filterDefinitions:
  - name: my-multi-tenant-filter
    type: MultiTenant
    config:
      prefixResourceNameSeparator: "." # <1>
      prefixResourceName: "myprefix" # <2>
----
<1> The separator used for the prefix.
If a separator is not specified, `-` is the default.
<2> (Optional) A custom prefix for resource names.
If specified, this value is used instead of the virtual cluster name as the prefix.
If not specified, the virtual cluster name is used (default behavior).
+
NOTE: Currently, only the prefix with separator is validated.

Refer to the {ProxyGuide} for more information about configuring the proxy.
