#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-certificate
spec:
  isCA: true
  commonName: mycluster-proxy.kafka
  secretName: kroxy-server-key-material
  privateKey:
    algorithm: RSA
    size: 4096
    # Note the cert-manager default is PKCS1. The tls.key generated won't work with Kroxylicious unless you put
    # Bouncy Castle in the classpath.  PKCS8 works without the classpath addition.
    encoding: PKCS8
  keystores:
   pkcs12:
     create: true
     passwordSecretRef:
       name: kroxy-server-keystore-password
       key: storePassword
  dnsNames:
    - my-cluster-proxy.kroxylicious
    - my-cluster-proxy-broker-0.kroxylicious
    - my-cluster-proxy-broker-1.kroxylicious
    - my-cluster-proxy-broker-2.kroxylicious
  usages:
    - server auth
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
