/*
 * Copyright Kroxylicious Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package io.kroxylicious.proxy.reload;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ReconfigureErrorTest {

    @Test
    void recordExposesIdentifierAndCause() {
        var cause = new RuntimeException("upstream unreachable");
        var error = new ReconfigureError("vc-checkout-prod", cause);
        assertThat(error.humanReadableIdentifier()).isEqualTo("vc-checkout-prod");
        assertThat(error.cause()).isSameAs(cause);
    }

    @Test
    void constructorRejectsNullIdentifier() {
        var cause = new RuntimeException();
        assertThatThrownBy(() -> new ReconfigureError(null, cause))
                .isInstanceOf(NullPointerException.class)
                .hasMessageContaining("humanReadableIdentifier");
    }

    @Test
    void constructorRejectsNullCause() {
        assertThatThrownBy(() -> new ReconfigureError("vc-1", null))
                .isInstanceOf(NullPointerException.class)
                .hasMessageContaining("cause");
    }

    @Test
    void equalsAndHashCodeUsedRecordAutoGenerated() {
        var cause = new RuntimeException("same");
        var a = new ReconfigureError("vc-1", cause);
        var b = new ReconfigureError("vc-1", cause);
        assertThat(a).isEqualTo(b);
        assertThat(a).hasSameHashCodeAs(b);
    }

    @Test
    void differingIdentifierMakesRecordsUnequal() {
        var cause = new RuntimeException();
        var a = new ReconfigureError("vc-1", cause);
        var b = new ReconfigureError("vc-2", cause);
        assertThat(a).isNotEqualTo(b);
    }
}
