:_mod-docs-content-type: ASSEMBLY

// file included in the following:
//
// record-validation-guide/index.adoc

[id='assembly-configuring-record-validation-filter-{context}']
= (Preview) Setting up the Record Validation filter

[role="_abstract"]
This procedure describes how to set up the Record Validation filter.
Provide the filter configuration and rules that the filter uses to check against Kafka record keys and values.

.Prerequisites

* An instance of Kroxylicious.
ifdef::OpenShiftOnly[]
For information on deploying Kroxylicious, see the {OperatorGuide}.
endif::OpenShiftOnly[]
ifndef::OpenShiftOnly[]
For information on deploying Kroxylicious, see the {ProxyGuide} or {OperatorGuide}.
endif::OpenShiftOnly[]
* A config map for Kroxylicious that includes the configuration for creating a virtual cluster.
* Apicurio Registry (if wanting to use Schema validation).

.Procedure

. Configure a `RecordValidation` type filter.

ifdef::include-platform-bare-metal[]
* In a standalone proxy deployment. See <<con-example-proxy-config-{context}>>
endif::[]
ifdef::include-platform-kubernetes[]
* In a Kubernetes deployment using a `KafkaProtocolFilter` resource. See <<con-example-kafkaprotocolfilter-resource-{context}>>
endif::[]


Replace the token `<rule definition>`  in the YAML configuration with either a Schema Validation rule or a JSON Syntax Validation rule depending on your requirements.

.Example Schema Validation Rule Definition

The Schema Validation rule validates that the key or value matches a schema identified by its global ID within an Apicurio Schema Registry.

If the key or value does not adhere to the schema, the record will be rejected.  

Additionally, if the kafka producer has embedded a global ID within the record it will be validated against the global ID defined by the rule. If they do not match, the record will be rejected.  See the 
{apicurio-docs}/getting-started/assembly-using-kafka-client-serdes.html#_consumer_schema_configuration[Apicurio documentation^] for details
on how the global ID could be embedded into the record. 
The filter supports extracting ID's from either the Apicurio `globalId` record header or from the initial bytes of the serialized content itself.

[source,yaml]
----
schemaValidationConfig:
    apicurioGlobalId: 1001                                       # <1>
    apicurioRegistryUrl: http://registry.local:8080              # <2>
allowNulls: true                                                 # <3>
allowEmpty: true                                                 # <4>
----
<1> Apicurio registry global ID identifying the schema that will be enforced.
<2> Apicurio Registry endpoint.
<3> if `true`, the validator allows keys and or values to be `null`. The default is `false`.
<4> if `true`, the validator allows keys and or values to be empty. The default is `false`.

NOTE: Schema validation mode currently has the capability to enforce only JSON schemas ({github-issues}/1431[issue])

.Example JSON Syntax Validation Rule Definition

The JSON Syntax Validation rule validates that the key or value contains only syntactically correct JSON.

[source,yaml]
----
syntacticallyCorrectJson:
    validateObjectKeysUnique: true                               # <1>
allowNulls: true                                                 # <2>
allowEmpty: true                                                 # <3>
----
<1> If `true`, the validator enforces that objects keys must be unique. The default is `false`.
<2> if `true`, the validator allows keys and or values to be `null`. The default is `false`.
<3> if `true`, the validator allows keys and or values to be empty. The default is `false`.

.Example JWS Signature Validation Rule Definition

The JWS Signature Validation rule validates that the configured Kafka record header contains a valid https://datatracker.ietf.org/doc/html/rfc7515[JSON Web Signature (JWS)] Signature.

WARNING: This validator does NOT include https://datatracker.ietf.org/doc/html/rfc7519[JSON Web Token (JWT)] validation (expiration, issuer, etc. are NOT checked).

[source,yaml]
----
jwsSignatureValidation:
    trustedJsonWebKeySet: |                                              # <1>
      {
        "keys": [
          {
            "kty": "RSA",
            "kid": "RSA JWK",
            "key_ops": [ "verify" ],
            "alg": "RS256",
            "n": "lx-5h_lkVJGc8-NxgKGkfxobBlM7DDCjqAloEieCf8c9KbPJ12V0Bm8arOX-lm0wRSLxmWzQ3NTM6S9pDbSc7fQt77THlMD1zEDMwIAJxfoMt3U_VrMHVdiOvO6YpU3jWBp7BfQNYHJjCSiaxIHqDPuDCh2GTflkU32Nfim7W3iLBuH4_K8ADYHz3QdeX29vzl49PDbUiiJEsjnEconsfuYjrFaN3uGn41mGzjedc7oxlcID8fDxq5bvZvOFBAIqdrxs5qPYw1QlVupB3LT0AMU1qKWOB_vkM1n54eDIxP9Xd__WnvX4wagYqA1OZ9LPBenhBX7_Rbnrap2QNQ58-Q",
            "e": "AQAB"
          },
          {
            "kty": "EC",
            "kid": "ECDSA JWK",
            "key_ops": [ "verify" ],
            "alg": "ES256",
            "x": "qqeGjWmYZU5M5bBrRw1zqZcbPunoFVxsfaa9JdA0R5I",
            "y": "wnoj0YjheNP80XYh1SEvz1-wnKByEoHvb6KrDcjMuWc",
            "crv": "P-256"
          }
        ]
      }
    algorithms:                                                   # <2>
      allowed:
          - ES256
          - RS256
    recordHeader:
      key: kroxylicious.io/jws                                    # <3>
      required: true                                              # <4>
    content:
      detached: false                                             # <5>
----
<1> Set of https://datatracker.ietf.org/doc/html/rfc7517[JSON Web Keys (JWK)] to use for verifying JWS Signatures.
<2> List of `allowed` and `denied` https://datatracker.ietf.org/doc/html/rfc7518#section-3.1[JSON Web Algorithms (JWA)].
    * (Default) If both `allowed` and `denied` are empty: block all algorithms.
    * If only `allowed` is filled: only allow the algorithms in `allowed`.
    * If only `denied` is filled: allow all algorithms except the ones in `denied`.
    * If both `allowed` and `denied` are filled: only allow the algorithms in `allowed`.
<3> Key of the Kafka record header containing the JWS. The default is `kroxylicious.io/jws`.
<4> If `true`, require the JWS Kafka record header to be present and valid. If `false`, only require the header to be valid _if it is present_ i.e. skip validation if the header is missing. The default is `true`.
<5> If `true`, the validator decodes the buffer into a UTF-8 string and uses that as the JWS Payload (see https://datatracker.ietf.org/doc/html/rfc7515#appendix-F[RFC 7515 Appendix F (Detached Content)]). The default is `false`.

ifdef::include-platform-bare-metal[]
include::../_modules/record-validation/con-example-proxy-config.adoc[leveloffset=+1]
endif::[]

ifdef::include-platform-kubernetes[]
include::../_modules/record-validation/con-example-kafkaprotocolfilter-resource.adoc[leveloffset=+1]
endif::[]