////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: ASSEMBLY

// file included in the following:
//
// index.adoc

[id='assembly-configuring-multi-tenancy-filter-{context}']
= (Preview) Setting up the Multi-tenancy filter

[role="_abstract"]
This procedure describes how to set up the Multi-tenancy filter by configuring it in Kroxylicious.
The filter dynamically prefixes resource names to create isolation between tenants using the same Kafka cluster.
The prefix representing a tenant is taken from the name of the virtual cluster representing the tenant, or from a custom value if `prefixResourceName` is specified.
For example, if the virtual cluster is named `tenant-1`, the prefix is `tenant-1` by default.
Each tenant must be represented by a unique virtual cluster, and virtual cluster names must be globally unique within the Kroxylicious configuration. 
This means that the same virtual cluster name cannot be used to represent different Kafka clusters.

.Prerequisites

* An instance of Kroxylicious.
ifdef::OpenShiftOnly[]
For information on deploying Kroxylicious, see the {OperatorGuide}.
endif::OpenShiftOnly[]
ifndef::OpenShiftOnly[]
For information on deploying Kroxylicious, see the {ProxyGuide} or {OperatorGuide}.
endif::OpenShiftOnly[]

.Procedure

. Configure a `MultiTenant` type filter.
ifdef::include-platform-bare-metal[]
* In a standalone proxy deployment. See <<con-example-proxy-config-{context}>>
endif::[]
ifdef::include-platform-kubernetes[]
* In a Kubernetes deployment using a `KafkaProtocolFilter` resource. See <<con-example-kafkaprotocolfilter-resource-{context}>>
endif::[]

. Verify that multi-tenancy filtering has been applied.
+
For example, create a topic through each virtual cluster and check that the topics are prefixed with the name of the corresponding virtual cluster.  
+

ifdef::include-platform-bare-metal[]
include::../_modules/multi-tenancy/con-example-proxy-config.adoc[leveloffset=+1]
endif::[]

ifdef::include-platform-kubernetes[]
include::../_modules/multi-tenancy/con-example-kafkaprotocolfilter-resource.adoc[leveloffset=+1]
endif::[]