#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  name: kroxylicious-service
spec:
  selector:
    app: kroxylicious
  type: LoadBalancer
  ports:
  - name: port-9092
    protocol: TCP
    port: 9092
    targetPort: 9092
