/*
 * Copyright Kroxylicious Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */

package io.kroxylicious.proxy.audit;

import java.time.Instant;
import java.util.Map;

import edu.umd.cs.findbugs.annotations.Nullable;

/**
 * Describes an auditable action that has been taken by the proxy or one of its plugins.
 */
public interface AuditableAction {

    /**
     * When the event happened.
     * @return The instant that the action happened.
     */
    Instant time();

    /**
     * What action was attempted.
     * @return The type of the event.
     * Plugins should package-qualify their actions.
     * Actions generated by the runtime are not prefixed.
     */
    String action();

    /**
     * What the outcome of the {@link #action()} was.
     * @return {@code null} if-and-only-if the action was successful, otherwise a
     * machine-readable indication of the reason why the action was unsuccessful.
     * This could be an exception class name or a Kafka error code.
     */
    @Nullable
    String status();

    /**
     * What the outcome of the {@link #action()} was.
     * @return {@code null} if the action was successful, otherwise an optional
     * human-readable explanation of why the action was unsuccessful.
     */
    @Nullable
    String reason();

    /**
     * Who initiated the action.
     * @return the actor that initiated the action.
     */
    Actor actor();

    /**
     * <p>The coordinates of the target object.
     * Each key represents scope (e.g., "vc", "topicId"), and the corresponding value is the unique identifier within that scope.</p>
     *
     * <p>Multiple scopes should be used when:</p>
     * <ul>
     *   <li>a single scope does not provide sufficient uniqueness;
     *     for example an identifier in the "topicName" scope
     *     is only unique within some Kafka cluster, so a scope identifying that
     *     cluster is needed to provide uniqueness.</li>
     *   <li>an identifier is unique but unhelpfully opaque;
     *     for example an identifier in the "topicId" scope is universally unique but does not identify
     *     the containing cluster</li>
     * </ul>
     *
     * <p>Plugins providing their own coordinates should package-prefix their scope names.</p>
     */
    Map<String, String> objectRef();

    /**
     * Contextual identifiers for correlating this action with external systems,
     * client requests, or distributed traces.
     */
    Correlation correlation();

    /**
     * {@link #action() action}-specific additional data about this action.
     * @return additional data about this action, or null if there is no additional information.
     */
    @Nullable
    Map<String, String> context();
}
