#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

kroxylicious.version=0.23.0-SNAPSHOT
git.commit.id=938cbde378a4d35e49abbe04bb32a5aba8ad4b2f
