#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

# Note the v1 in the filename refers to the version of the CustomResourceDefinition
# not any of the versions of API being defined.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: virtualkafkaclusters.kroxylicious.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kroxylicious.io
  scope: Namespaced
  names:
    plural: virtualkafkaclusters
    singular: virtualkafkacluster
    kind: VirtualKafkaCluster
    shortNames:
      - vkc
    categories:
      - kroxylicious
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - name: Proxy
          description: The name of the proxy that this virtual cluster is part of.
          jsonPath: ".spec.proxyRef.name"
          type: string
          priority: 0
        - name: KafkaService
          description: The name of the kafka service that this virtual cluster exposes.
          jsonPath: ".spec.targetKafkaServiceRef.name"
          type: string
          priority: 0
        - name: ResolvedRefs
          description: Whether the other resources referenced by this virtual cluster can be found.
          jsonPath: ".status.conditions[?(@.type==\"ResolvedRefs\")].status"
          type: string
          priority: 0
        - name: Accepted
          description: Whether the virtual cluster has been accepted by the proxy.
          jsonPath: ".status.conditions[?(@.type==\"Accepted\")].status"
          type: string
          priority: 0
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
            spec:
              type: object
              required: ["proxyRef", "targetKafkaServiceRef", "ingressRefs"]
              properties:
                proxyRef:
                  type: object
                  required: [ "name" ]
                  properties:
                    name:
                      maxLength: 253
                      minLength: 1
                      type: string
                targetKafkaServiceRef:
                  type: object
                  required: [ "name" ]
                  properties:
                    group:
                      type: string
                      pattern: ^kroxylicious[.]io$
                    kind:
                      type: string
                      pattern: ^KafkaService$
                    name:
                      maxLength: 253
                      minLength: 1
                      type: string
                ingressRefs:
                  type: array
                  minItems: 1
                  description: -|
                    IngressRefs specifies an array of references to KafkaProxyIngresses. It must contain at
                    least one element.
                  items:
                    type: object
                    required: [ "name" ]
                    properties:
                      name:
                        description: Name is the name of the referent
                        maxLength: 253
                        minLength: 1
                        type: string
                filterRefs:
                  description: The filters to be used for this cluster. Each filter is a separate resource.
                  type: array
                  items:
                    type: object
                    required: [ "name" ]
                    properties:
                      name:
                        maxLength: 253
                        minLength: 1
                        type: string
            status:
              type: object
              properties:
                observedGeneration:
                  description: |
                    The metadata.generation that was observed during the last reconciliation by the operator.
                  type: integer
                conditions:
                  # Mapped to Java type io.kroxylicious.kubernetes.api. io.kroxylicious.kubernetes.api.common.common.Condition
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        description: |
                          lastTransitionTime is the last time the condition transitioned from one status to another. 
                          This should be when the underlying condition changed. 
                          If that is not known, then using the time when the API field changed is acceptable.
                        type: string
                        format: date-time
                      message:
                        description: |
                          message is a human readable message indicating details about the transition. 
                          This may be an empty string.
                        type: string
                        default: ""
                        nullable: false
                      observedGeneration:
                        description: |
                          observedGeneration represents the .metadata.generation that the condition was set based upon. 
                          For instance, if .metadata.generation is currently 12, but the 
                          .status.conditions[x].observedGeneration is 9, the condition is out of date with 
                          respect to the current state of the instance.
                        type: integer
                        nullable: false
                      reason:
                        description: |
                          reason contains a programmatic identifier indicating the reason for the condition's last transition. 
                          Producers of specific condition types may define expected values and meanings for this field, 
                          and whether the values are considered a guaranteed API. 
                          The value should be a CamelCase string. 
                          This field may not be empty.
                        type: string
                        nullable: false
                      status:
                        description: status of the condition, one of True, False, Unknown.
                        type: string
                        enum: [ "True", "False", "Unknown" ]
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        type: string
                    required:
                      - lastTransitionTime
                      - observedGeneration
                      - reason
                      - message
                      - type
                ingresses:
                  description: -|
                    Lists the ingresses that have been associated with the virtual cluster.
                  type: array
                  default: []
                  items:
                    type: object
                    required: [ "name" ]
                    properties:
                      name:
                        description: The name of the ingress.
                        type: string
                      bootstrapServer:
                        description: -|
                          The address (host and port) that a Kafka client would use make its initial connection to the
                          virtual cluster. This property will be absent if the address is not yet available.
                        type: string
