#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  name: kroxylicious-service
spec:
  type: NodePort
  selector:
    app: kroxylicious
  ports:
  - name: metrics
    protocol: TCP
    port: 30090
    targetPort: 9190
    nodePort: 30090

  - name: port-30192
    protocol: TCP
    port: 30192
    targetPort: 30192
    nodePort: 30192

  - name: port-30193
    protocol: TCP
    port: 30193
    targetPort: 30193
    nodePort: 30193

  - name: port-30194
    protocol: TCP
    port: 30194
    targetPort: 30194
    nodePort: 30194

  - name: port-30195
    protocol: TCP
    port: 30195
    targetPort: 30195
    nodePort: 30195

