// file included in the following:
//
// assembly-built-in-filters.adoc

[id='con-schema-validation-{context}']
= Schema Validation

[role="_abstract"]
Schema validation filter that enables validating records using an existing schema in https://www.apicur.io/registry/[Apicurio Registry].

== How to use the filter

There is just one step to use the filter.

1. <<Configuring virtual clusters>>
2. Configuring the filter within Kroxylicious.

=== Configuring the filter within Kroxylicious.

[source,yaml]
filters:
  - type: ProduceValidationFilterFactory
    config:
        rules:
        - topicNames:
            - test-topic
            valueRule:
                schemaValidationConfig:
                    apicurioGlobalId: 1
                    apicurioRegistryUrl: http://localhost:8080


The apicurioGlobalId parameter is the global identifier of the schema that will be used to validate the value of the records in test-topic. The second parameter, apicurioRegistryUrl, is the URL of your Apicurio Registry instance.

With this configuration, the values of all the records you produce to the test-topic 1 will be validated using the schema present in Apicurio Registry with global identifier 1.
