////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// Module included in the following _assemblies:
//
// _assemblies/assembly-operator-install.adoc

[id='con-operator-release-artifacts-{context}']
= Operator release artifacts

[role="_abstract"]
ifdef::IncludeSingleYamlFileManifest[]
Kroxylicious provides multiple distribution formats to suit different installation workflows. You can choose between archive distributions (zip or tar.gz) or single-file rendered YAML manifests.
endif::IncludeSingleYamlFileManifest[]

ifndef::IncludeSingleYamlFileManifest[]
Kroxylicious provides archive distributions (zip or tar.gz) containing the installation resources.
endif::IncludeSingleYamlFileManifest[]

== Archive distributions

Archive distributions are available in zip and tar.gz formats from {github-release-link}:

Zip archive:: link:{OperatorAssetZipLink}[{OperatorAssetZipFileName}] contains CRD definitions, installation files, examples, and documentation.

Tar.gz archive:: link:{OperatorAssetTgzLink}[{OperatorAssetTgzFileName}] is the same content as the zip archive, provided in tar.gz format for environments that prefer this format.

ifdef::IncludeSingleYamlFileManifest[]

== Single YAML file manifest

A single YAML file manifest is available from {github-release-link}:

Full install manifest:: link:{OperatorInstallManifestLink}[{OperatorInstallManifestFileName}] contains all required resources (CRDs, Namespace, ServiceAccount, ClusterRole, ClusterRoleBinding, Deployment).

CRDs-only manifest:: link:{OperatorCrdsManifestLink}[{OperatorCrdsManifestFileName}] contains only CustomResourceDefinition resources.

Examples archive:: link:{OperatorExamplesZipLink}[{OperatorExamplesZipFileName}] contains example configurations and custom resources.
endif::IncludeSingleYamlFileManifest[]
