// file included in the following:
//
// assembly-configuring-oauth-bearer-validation-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for Oauth Bearer validation:

.Example `filterDefinitions` configuration
[source, yaml]
----
filterDefinitions:
  - name: my-oauth-filter
    type: OauthBearerValidation
    config:
      jwksEndpointUrl: https://oauth/JWKS   #<1>
      jwksEndpointRefreshMs: 3600000        #<2>
      jwksEndpointRetryBackoffMs: 100       #<3>
      jwksEndpointRetryBackoffMaxMs: 10000  #<4>
      scopeClaimName: scope                 #<5>
      subClaimName: sub                     #<6>
      authenticateBackOffMaxMs: 60000       #<7>
      authenticateCacheMaxSize: 1000        #<8>
      expectedAudience: https://first.audience, https//second.audience #<9>
      expectedIssuer: https://your-domain.auth/ #<10>
----

<1> The OAuth/OIDC provider URL from which the provider's JWKS (JSON Web Key Set) can be retrieved.
<2> The (optional) value in milliseconds for the broker to wait between refreshing its JWKS (JSON Web Key Set) cache that contains the keys to verify the signature of the JWT.
<3> The (optional) value in milliseconds for the initial wait between JWKS (JSON Web Key Set) retrieval attempts from the external authentication provider.
<4> The (optional) value in milliseconds for the maximum wait between attempts to retrieve the JWKS (JSON Web Key Set) from the external authentication provider.
<5> This (optional) setting can provide a different name to use for the scope included in the JWT payload's claims.
<6> This (optional) setting can provide a different name to use for the subject included in the JWT payload's claims.
<7> The (optional) maximum value in milliseconds to limit the client sending authenticate request. Setting 0 will never limit the client. Otherwise, an exponential delay is added to each authenticate request until the authenticateBackOffMaxMs has been reached.
<8> The (optional) maximum number of failed tokens kept in cache.
<9> The (optional) comma-delimited setting for the broker to use to verify that the JWT was issued for one of the expected audiences.
<10> The (optional) setting for the broker to use to verify that the JWT was created by the expected issuer.

Refer to the {ProxyGuide} for more information about configuring the proxy.
