////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-oauth-bearer-validation-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.

Here's a complete example of a `filterDefinitions` entry configured for Oauth Bearer validation:

.Example `filterDefinitions` configuration
[source, yaml]
----
filterDefinitions:
  - name: my-oauth-filter
    type: OauthBearerValidation
    config:
      jwksEndpointUrl: https://oauth/JWKS
      jwksEndpointRefreshMs: 3600000
      jwksEndpointRetryBackoffMs: 100
      jwksEndpointRetryBackoffMaxMs: 10000
      scopeClaimName: scope
      subClaimName: sub
      authenticateBackOffMaxMs: 60000
      authenticateCacheMaxSize: 1000
      expectedAudience: https://first.audience, https//second.audience
      expectedIssuer: https://your-domain.auth/
----
where:

* `jwksEndpointUrl` is the OAuth/OIDC provider URL from which the provider's JWKS (JSON Web Key Set) can be retrieved.
* `jwksEndpointRefreshMs` is the (optional) value in milliseconds for the broker to wait between refreshing its JWKS (JSON Web Key Set) cache that contains the keys to verify the signature of the JWT.
* `jwksEndpointRetryBackoffMs` is the (optional) value in milliseconds for the initial wait between JWKS (JSON Web Key Set) retrieval attempts from the external authentication provider.
* `jwksEndpointRetryBackoffMaxMs` is the (optional) value in milliseconds for the maximum wait between attempts to retrieve the JWKS (JSON Web Key Set) from the external authentication provider.
* `scopeClaimName` is the (optional) setting can provide a different name to use for the scope included in the JWT payload's claims.
* `subClaimName` is the (optional) setting can provide a different name to use for the subject included in the JWT payload's claims.
* `authenticateBackOffMaxMs` is the (optional) maximum value in milliseconds to limit the client sending authenticate request. Setting 0 will never limit the client. Otherwise, an exponential delay is added to each authenticate request until the authenticateBackOffMaxMs has been reached.
* `authenticateCacheMaxSize` is the (optional) maximum number of failed tokens kept in cache.
* `expectedAudience` is the (optional) comma-delimited setting for the broker to use to verify that the JWT was issued for one of the expected audiences.
* `expectedIssuer` is the (optional) setting for the broker to use to verify that the JWT was created by the expected issuer.

Refer to the {ProxyGuide} for more information about configuring the proxy.
