////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-preparing-hashicorp-vault.adoc

[id='con-vault-setup-{context}']
= Enable the Transit Engine

[role="_abstract"]
The filter integrates with the {hashicorp-vault}/docs/secrets/transit[HashiCorp Vault *Transit Engine*].
Vault does not enable the Transit Engine by default.
It must be {hashicorp-vault}/docs/secrets/transit#setup[enabled] before it can be used by the filter.

== Vault Transit Engine URL

The Vault Transit Engine URL is required so the filter knows the location of the Transit Engine within the
Vault instance.

The URL is formed from the concatenation of the `Api Address` (reported by Vault during
{hashicorp-vault}/tutorials/getting-started/getting-started-dev-server#starting-the-dev-server[startup^]) with the
complete path to Transit Engine, including the name of the engine itself. 

If {hashicorp-vault}/docs/enterprise/namespaces[Namespacing] is used on the Vault instance, the path must include the
namespaces. The URL will end with `/transit` unless the `-path` parameter was used when
{hashicorp-vault}/docs/secrets/transit#setup[enabling the engine].

If namespacing is not in use, the URL looks like this:

[source,shell]
----
https://myvaultinstance:8200/v1/transit
----

If namespacing is in use, the path must include the namespaces. For example, if there is a parent namespace is `a` and
a child namespace is `b`, the URL looks like this:

[source,shell]
----
https://myvaultinstance:8200/v1/a/b/transit
----

If the name of the Transit engine was changed (using the `-path` argument to the `vault secrets enable transit` command)
the URL looks like this:

[source,shell]
----
https://myvaultinstance:8200/v1/mytransit
----

== Role of the administrator

To use the filter, an administrator or an administrative process must create the encryption keys within Vault, which
are used by the xref:con-record-encryption-overview-{context}[envelope encryption] process.

The organization deploying the Record Encryption filter is responsible for managing this administrator or process.

The administrator must have permissions to create keys beneath `transit/keys/KEK-*` in the Vault hierarchy.

As a guideline, the minimal Vault policy required by the administrator is as follows:

[source,shell]
----
path "transit/keys/KEK-*" {
  capabilities = ["read", "write"]
}
----

== Establish an application identity for the filter

The filter must authenticate to Vault in order to perform envelope encryption operations, such as generating and decrypting DEKs.
Therefore, a Vault identity with sufficient permissions must be created for the filter.

First, create a Vault policy for the filter:

[source,shell]
----
vault policy write kroxylicious_encryption_filter_policy - << EOF
path "transit/keys/KEK-*" {
  capabilities = ["read"]
}
path "/transit/datakey/plaintext/KEK-*" {
  capabilities = ["update"]
}
path "transit/decrypt/KEK-*" {
  capabilities = ["update"]
}
EOF
----

Kroxylicious supports two authentication mechanisms for Vault:

* Token Authentication
* Kubernetes Authentication

=== Token Authentication

Create a {hashicorp-vault}/docs/concepts/tokens#periodic-tokens[Periodic] (long-lived) Vault Token
for the filter:

[source,shell]
----
vault token create -display-name "kroxylicious record encryption" \
                   -policy=kroxylicious_encryption_filter_policy \
                   -period=768h \
                   -no-default-policy \
                   -orphan

----
where:

* The `-period` switch causes the token to be periodic (with every renewal using the given period).
* The `-no-default-policy` switch detaches the policy from the default policy.  This is done so the token has least-privilege.
* The `-orphan` switch create the token with no parent. This is done so that expiration of a parent won't expire the token used by the filter.

NOTE: The example token create command illustrates the use of `-no-default-policy`
and `-orphan`. The use of these flags is not functionally important.  
You may adapt the configuration of the token to suit the standards required by your organization.

The `token create` command yields the `token`. The `token` value is required later when configuring the vault within the
filter.

[source]
----
token              hvs.CAESIFJ_HHo0VnnW6DSbioJ80NqmuYm2WlON-QxAPmiJScZUGh4KHGh2cy5KdkdFZUJMZmhDY0JCSVhnY2JrbUNEWnE
token_accessor     4uQZJbEnxW4YtbDBaW6yVzwP
token_policies     [kroxylicious_encryption_filter_policy]
----

The token must be {hashicorp-vault}/docs/concepts/tokens#token-time-to-live-periodic-tokens-and-explicit-max-ttls[renewed]
before expiration.  
It is the responsibility of the administrator to do this.

This can be done with a command like the following:

[source,shell]
----
vault token renew --accessor <token_accessor>
----

=== Kubernetes Authentication

When running Kroxylicious in Kubernetes, you can use the Vault {hashicorp-vault}/docs/auth/kubernetes[Kubernetes auth method] to authenticate using the Kubernetes ServiceAccount token.

==== 1. Create Kubernetes ServiceAccount and RBAC Permissions

Create a dedicated `ServiceAccount` for Kroxylicious and bind it to the `system:auth-delegator` `ClusterRole` so Vault can validate the ServiceAccount token using Kubernetes TokenReview API:

[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kroxylicious-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kroxylicious-vault-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: kroxylicious-sa
    namespace: default
----

==== 2. Configure Vault Kubernetes Auth Engine

Enable and configure the Kubernetes authentication method in Vault:

[source,shell]
----
# 1. Enable the Kubernetes authentication method in Vault
vault auth enable kubernetes

# 2. Configure Vault with your Kubernetes cluster API server address
vault write auth/kubernetes/config \
    kubernetes_host="https://kubernetes.default.svc:443"

# 3. Create a Vault role bound to the Kroxylicious ServiceAccount and policy
vault write auth/kubernetes/role/kroxylicious-role \
    bound_service_account_names=kroxylicious-sa \
    bound_service_account_namespaces=default \
    policies=kroxylicious_encryption_filter_policy \
    ttl=24h
----

== Testing the application identity for the filter using the CLI

To test whether the application identity and the policy are working correctly, a
{github-raw-root}/scripts/validate_vault_token.sh[script] can be used.

First, as the administrator, create a KEK in the hierarchy at this path `transit/keys/KEK-testkey`.

[source,shell]
----
VAULT_TOKEN=<kroxylicious encryption filter token> validate_vault_token.sh <kek path>
----

The script should respond `Ok`.  
If errors are reported check the policy/token configuration.

`transit/keys/KEK-testkey` can now be removed.

