:_mod-docs-content-type: PROCEDURE

// file included in the following:
//
// assembly-hashicorp-vault.adoc

[id='con-vault-key-creation-{context}']
= Creating HashiCorp Vault keys

[role="_abstract"]
This procedure describes how to create AES-256 symmetric keys for use with the Record Encryption filter. The procedure establishes a naming convention for keys, then uses the HashiCorp CLI to create a key with an optional rotation policy.

.Prerequisites

* Access to the HashiCorp Vault CLI with permissions to create keys.
* Familiarity with basic HashiCorp Vault Transit Engine key management operations.

.Procedure

. Establish a naming convention for keys to ensure that the filter’s keys remain separate from those used by other systems.
+
In this example, a `KEK-` prefix is used for filter key names. Adjust the naming convention as needed.

. Create a symmetric key:
+
[source, shell]
----
vault write -f transit/keys/KEK-trades type=aes256-gcm96 auto_rotate_period=90d
----
* The key type must be `aes256-gcm96`, which is the default type for the Transit Engine.
* (Optional) The `auto_rotate_period` parameter enables automatic 90-day key rotation. Adjust the rotation period if required.

TIP: It is recommended to use a key rotation policy.
