:_mod-docs-content-type: PROCEDURE

// file included in the following:
//
// assembly-hashicorp-vault.adoc

[id='con-vault-key-creation-{context}']
= Creating HashiCorp Vault keys

[role="_abstract"]
This procedure describes how to create AES-256 symmetric keys for use with the Record Encryption filter. The process establishes a naming convention for keys, then uses the HashiCorp CLI to create a key with a 90-day rotation policy following the key naming convention.

.Prerequisites

* Access to the HashiCorp CLI.
* Sufficient permissions to create keys.

.Procedure

. Establish a naming convention for keys to keep the filter’s keys separate from those used by other systems.
+
Here, we use a prefix of KEK- for filter key name. Adjust the instructions if a different naming convention is used.

. Create a symmetric key
+
[source, shell]
----
vault write -f transit/keys/KEK-trades type=aes256-gcm96 auto_rotate_period=90d
----
* The key type must be `aes256-gcm96`, which is Vault's default key type.

TIP: It is recommended to use a key rotation policy.
