#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: Secret
metadata:
  name: alice-password
  namespace: my-proxy
type: Opaque
stringData:
  password: "changeit"
