#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: bob
  namespace: my-proxy
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512 
    password:
      valueFrom:
        secretKeyRef:
          name: bob-password
          key: password
