:_mod-docs-content-type: CONCEPT

[id='con-configuring-target-cluster-connections-{context}']
= Securing connections to target clusters

[role="_abstract"]
To secure connections from the virtual cluster to the upstream cluster, configure the target cluster's TLS setting by
doing the following:

* If the upstream is using a private CA, use the `trust` properties to configure a truststore for the target cluster.

* If you want to use mutual TLS, specify the certificate with the `key` property to identify the virtual cluster to the upstream.

* If required, you can restrict the TLS protocols and cipher suites that are used to form the TLS connection.

NOTE: TLS is recommended on Kafka clients and virtual clusters for production configurations.

Examples below illustrate how these steps may be done.

Using an empty object (`{}`) enables TLS using the platform's defaults. This means that platform trust, and
default protocols and cipher suites will be used. This option is suitable if the upstream cluster is using a TLS
certificate signed by a public CA and the platform's defaults are suitable.

.Example enabling TLS for a target cluster using platform defaults
[source,yaml]
----
# ...
virtualClusters:
  - name: my-cluster-proxy
    # ...
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls: {}
# ...
----

If it is using a TLS certificate signed by a private CA, you must add truststore configuration for the target cluster.
The example illustrates using PKCS #12 format. PEM format is supported too.

.Example specifying a truststore
[source,yaml]
----
# ...
virtualClusters:
  - name: my-cluster-proxy
    # ...
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        trust:
          storeFile: <path>/trust.p12 # <1>                
          storePassword:
            passwordFile: <path>/store.password # <2>    
          storeType: PKCS12 # <3>
# ...
----
<1> PKCS #12 store for the public CA certificate of the Kafka cluster.
<2> Password to access the public Kafka cluster CA certificate.
<3> (Optional) Keystore type. If a keystore type is not specified, the default JKS (Java Keystore) type is used.

For mutual TLS, add a keystore configuration for the virtual cluster.  
The following example uses a PEM format server certificate and key pair. 
PKCS #12 keystore format is supported too.

.Example configuring mutual TLS
[source,yaml]
----
# ...
virtualClusters:
  - name: my-cluster-proxy
    # ...
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        key:
          privateKeyFile: <path>/client.key # <1>
          certificateFile: <path>/client.crt # <2>
# ...
----
<1> Private key of the virtual cluster.
<2> Public CA certificate of the virtual cluster.

The TLS protocols and cipher suites available to the TLS connection may also be configured.

.Example restricting TLS protocols using an allow list
[source,yaml]
----
# ...
virtualClusters:
  - name: my-cluster-proxy
    # ...
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        # ...
        protocols:
          allowed:  # <1>
          - TLSv1.3
          - TLSv1.2
----
<1> List of allowed TLS protocols.

.Example restricting TLS protocols using a deny list

[source,yaml]
----
virtualClusters:
  - name: my-cluster-proxy
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        # ...
        protocols:
          denied:  # <1>
          - TLSv1.1
----
<1> List of disallowed TLS protocols.

.Example restricting cipher suites using an allow list

[source,yaml]
----
virtualClusters:
  - name: my-cluster-proxy
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        # ...
        cipherSuites:
          allowed:  # <1>
          - TLS_ECDHE_ECDSA_WITH_AES_256_CCM
          - TLS_ECDHE_ECDSA_WITH_AES_128_CCM
----
<1> List of allowed cipher suites.

.Example restricting cipher suites using a deny list

[source,yaml]
----
virtualClusters:
  - name: my-cluster-proxy
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        # ...
        cipherSuites:
          denied:  # <1>
          - TLS_KRB5_WITH_3DES_EDE_CBC_MD5
----
<1> List of disallowed cipher suites.

For the purposes of testing (that is, outside a production environment), you can set the `insecure` property to `true`
to disable TLS trust checks (hostname verification and certificate validation) so that the Kroxylicious can connect to
any Kafka cluster.

.Example configuration to disable TLS trust checks
[source,yaml]
----
virtualClusters:
  - name: my-cluster-proxy
    targetCluster:
      bootstrapServers: dev-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls:
        trust:
          insecure: true
# ...
----