////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

[id='con-configuration-outline-{context}']
= Outline of a Kroxylicious configuration

[role="_abstract"]
The following example shows the overall outline of a simple Kroxylicious configuration. 
While not complete (as indicated by `# ...`), it illustrates the essential structure.

[id='con-basic-structure-{context}']
.Basic outline of a Kroxylicious configuration
[source,yaml]
----
filterDefinitions:
  - name: example
    type: org.example.filter.Example
    config:
      # ...
defaultFilters:
  - example
virtualClusters:
  - name: my-cluster-proxy
    targetCluster:
      # ...
    gateways:
    - name: ...
      # ...
    subjectBuilder:
      # ...

# ...
----
where:

* `filterDefinitions` defines the list of filter definitions. Each filter definition comprises:
** A `name` which identifies the filter definition. Name is required. It must be unique amongst all the other filters in the list.
** A `type` that specifies the filter implementation class. Required.
** `config` provides configuration to the filter. Usually required for non-trivial filters.
   The configuration required depends on the filter implementation.
* `defaultFilters` defines an ordered list of filters that the traffic sent to the virtual cluster will pass through.
  It's possible to override this list at the virtual cluster level.
* `virtualClusters` List of virtual clusters definition providing cluster-specific configurations.
** A `name` which identifies the virtual cluster. Name is required. It must be unique amongst all the other virtual cluster in the list.
** `targetCluster` Configuration of the actual Kafka cluster that is proxied by the 'my-cluster-proxy' virtual cluster.
** `gateways` Configuration of the gateways for this virtual cluster.
** `subjectBuilder` (Optional) Configuration for the transport subject builder.
