////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// kroxylicious-operator/_assemblies/assembly-operator-secure-client-proxy-connection.adoc

[id='con-virtualkafkacluster-mtls-{context}']
= Mutual TLS configuration for client-to-proxy connections

[role="_abstract"]
You can configure a virtual cluster ingress to request or require Kafka clients to authenticate to the proxy using TLS.
This configuration is known as mutual TLS (mTLS), because both the client and the proxy authenticate each other using TLS.

.Example `VirtualKafkaCluster` configuration requiring clients to present a trusted certificate provided from a `ConfigMap`
[source,yaml]
----
kind: VirtualKafkaCluster
metadata:
  # ...
spec:
  # ...
  ingresses:
    - ingressRef:
        name: cluster-ip
      tls:
        certificateRef:
          # ...
        trustAnchorRef:
          kind: ConfigMap
          name: trusted-cas
          key: trusted-cas.pem
        tlsClientAuthentication: REQUIRED
----
where:

* `trustAnchorRef`  references a separate Kubernetes resource containing the CA certificates to trust.
** `kind` is optional and defaults to `ConfigMap`.
* `tlsClientAuthentication`  specifies whether client authentication is required (`REQUIRED`), requested (`REQUESTED`), or disabled (`NONE`). If a `trustAnchorRef` is specified, the default is `REQUIRED`.

.Example `VirtualKafkaCluster` configuration requiring clients to present a trusted certificate provided from a `Secret`

[source,yaml]
----
kind: VirtualKafkaCluster
metadata:
  # ...
spec:
  # ...
  ingresses:
    - ingressRef:
        name: cluster-ip
      tls:
        certificateRef:
          # ...
        trustAnchorRef:
          kind: Secret
          name: trusted-cas
          key: trusted-cas.pem
        tlsClientAuthentication: REQUIRED
----
where:

* `trustAnchorRef` references a separate Kubernetes resource containing the trusted CA certificates.
** `kind` specifies `Secret`.
* `tlsClientAuthentication` specifies whether client authentication is required (`REQUIRED`), requested (`REQUESTED`), or disabled (`NONE`). If a `trustAnchorRef` is specified, the default is `REQUIRED`.
