////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// kroxylicious-operator/_assemblies/assembly-operator-secure-client-proxy-connection.adoc

[id='con-virtualkafkacluster-tls-cipher-{context}']
= TLS cipher suite configuration for client-to-proxy connections

[role="_abstract"]
include::../../_snippets/snip-tls-cipher-suite.adoc[]

You can restrict which TLS cipher suites the proxy uses when negotiating client-to-proxy connections by configuring the `cipherSuites` property.

.Example `VirtualKafkaCluster` configuration using cipherSuites to allow specific ciphers
[source,yaml]
----
kind: VirtualKafkaCluster
metadata:
  # ...
spec:
  # ...
  ingresses:
    - ingressRef:
        name: cluster-ip
      tls:
        certificateRef:
          # ...
        cipherSuites:
          allowed:
           - TLS_AES_128_GCM_SHA256
           - TLS_AES_256_GCM_SHA384

----
where:

* `cipherSuites` configures the cipher suites used by the proxy.
** `allowed` lists the cipher suites explicitly allowed for TLS negotiation.

Alternatively, you can use `denied` to specify cipher suites to exclude.
The names of the cipher suites supported depend on the JVM in the proxy container image.

[role="_additional-resources"]
.Additional resources

* {cipherSuiteNames}
