////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// kroxylicious-operator/assemblies/assembly-operator-deploy-a-proxy.adoc

[id='con-virtualkafkacluster-overview-{context}']
= Virtual cluster configuration

[role="_abstract"]
A `VirtualKafkaCluster` resource defines a logical Kafka cluster that is accessible to clients over the network.

The virtual cluster references the following resources, which must be in the same namespace:

* A `KafkaProxy` resource that the proxy is part of.
* One or more `KafkaProxyIngress` resources that expose the virtual cluster to Kafka clients and provide virtual-cluster-specific configuration to the ingress (such as TLS certificates and other parameters).
* A `KafkaService` resource that defines the backend Kafka cluster.
* One or more `KafkaProtocolFilter` resources that filter the Kafka protocol traffic between clients and the backend Kafka cluster.
The order of the filters in the `filterRefs` array defines the order that the filters are applied.
Client requests pass through the filters starting at index `0`, then `1`, and continuing to index `n`.
Broker responses pass through the same filters in the reverse order.
If the `filterRefs` array is empty (or null), the traffic will pass through the cluster unchanged.

The following example shows configuration for a `VirtualKafkaCluster` that is exposed it to Kafka clients running on the same Kubernetes cluster.
Protocol traffic is filtered by the `my-filter` filter.

.Example `VirtualKafkaCluster` configuration with a single ingress and filter.
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef:
    name: simple
  targetKafkaServiceRef:
    name: my-cluster
  ingresses:
    - ingressRef:
        name: cluster-ip
  filterRefs:
    - name: my-filter

----
where:

* `proxyRef` identifies the `KafkaProxy` resource that this virtual cluster is part of.
* `targetKafkaServiceRef` specifies the `KafkaService` that defines the Kafka cluster proxied by the virtual cluster.
* `ingressRef` defines the ingresses that expose the virtual cluster. Each ingress references a `KafkaProxyIngress` by name.
* `filterRefs` specifies the list of filters applied to Kafka protocol traffic.

The following example shows configuration for a `VirtualKafkaCluster` that is exposed to Kafka clients running both on and off the cluster, using TLS.
Because TLS is used, the ingress configuration must reference a TLS server certificate.
This example has two filters.

.Example `VirtualKafkaCluster` configuration with two TLS-enabled ingresses
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef:
    name: simple
  targetKafkaServiceRef:
    name: my-cluster
  ingresses:
    - ingressRef:
        name: cluster-ip
        certificateRef:
          name: 'cluster-ip-server-cert'
          kind: Secret
    - ingressRef:
        name: load-balancer
        certificateRef:
          name: 'external-server-cert'
          kind: Secret
  filterRefs:
    - name: my-filter-1
    - name: my-filter-2
----
where:

* `name` References a secret containing the server certificate for the `clusterIP` ingress.
* `name` References a secret containing the server certificate for the `loadBalancer` ingress.

include::./con-virtualkafkacluster-clusterip-generate-tls-certificates.adoc[leveloffset=+1]
include::./con-virtualkafkacluster-loadbalancer-generate-tls-certificates.adoc[leveloffset=+1]
include::./proc-virtualkafkacluster-loadbalancer-dns-config.adoc[leveloffset=+1]
include::./con-virtualkafkacluster-openshiftroute-generate-tls-certificates.adoc[leveloffset=+1]
