////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// kroxylicious-operator/_assemblies/assembly-operator-secure-client-proxy-connection.adoc

[id='con-virtualkafkacluster-tls-protocol-{context}']
= TLS version configuration for client-to-proxy connections

[role="_abstract"]
include::../../_snippets/snip-tls-protocol-versions.adoc[]

You can restrict which TLS protocol versions the proxy supports for client-to-proxy connections by configuring the `protocols` property.

.Example `VirtualKafkaCluster` with restricted TLS protocol versions
[source,yaml]
----
kind: VirtualKafkaCluster
metadata:
  # ...
spec:
  # ...
  ingresses:
    - ingressRef:
        name: cluster-ip
      tls:
        certificateRef:
          # ...
        protocols:
          allowed:
            - TLSv1.3
----
where:

* `protocols` configures the TLS protocol versions used by the proxy.
** `allowed` lists the protocol versions explicitly allowed for TLS negotiation.

Alternatively, you can use `denied` to specify protocol versions to exclude.

The names of the TLS protocol versions supported depend on the JVM in the proxy container image.

[role="_additional-resources"]
.Additional resources

* {tlsProtocolNames}
