////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

[id='con-configuration-outline-{context}']
= Outline of a Kroxylicious configuration

[role="_abstract"]
The following example shows the overall outline of a simple Kroxylicious configuration. 
While not complete (as indicated by `# ...`), it illustrates the essential structure.

[id='con-basic-structure-{context}']
.Basic outline of a Kroxylicious configuration
[source,yaml]
----
filterDefinitions:
  - name: example
    type: org.example.filter.Example
    config:
      # ...
defaultFilters:
  - example
virtualClusters:
  - name: my-cluster-proxy
    targetCluster:
      # ...
    gateways:
    - name: ...
      # ...
    subjectBuilder:
      # ...
proxyProtocol: # <10>
  enabled: false

# ...
----
where:

* `filterDefinitions` lists filter definitions. Each definition comprises:
** (Required) A `name` that identifies the filter. Must be unique within the list.
** A `type` that specifies the filter implementation class. Required.
** `config` provides filter configuration for non-trivial filters.
   The required configuration depends on the filter implementation.
* `defaultFilters` defines an ordered list of filters that the traffic sent to the virtual cluster will pass through.
  You can override this list at the virtual cluster level.
* `virtualClusters` defines the virtual clusters and their cluster-specific configurations.
** (Required) A `name` that identifies the virtual cluster. Must be unique within the list.
** `targetCluster` defines the Kafka cluster that the virtual cluster (`my-cluster-proxy`) proxies.
** `gateways` defines the gateways configuration for this virtual cluster.
** `subjectBuilder` (Optional) defines the transport subject builder configuration.
** `proxyProtocol` (Optional) Enable HAProxy PROXY protocol decoding when deployed behind a PROXY protocol-capable load balancer.
