////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

[id='con-checking-kafkaproxyingress-status-{context}']
= Checking the status of the `KafkaProxyIngress` resource

[role="_abstract"]
The status of a `KafkaProxyIngress` resource provides feedback on its configuration through a set of conditions.
These include the `ResolvedRefs` condition, which indicates whether all referenced resources exist.

When you create a `KafkaProxyIngress`, the operator checks whether a `KafkaProxy` corresponding to the `spec.proxyRef` exists.
The result is reported in `status.conditions` with a `ResolvedRefs` condition accordingly.

.Example `KafkaProxyIngress` status when `spec.proxyRef` exists
[source,yaml]
----
kind: KafkaProxyIngress
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: cluster-ip
  namespace: my-proxy
  generation: 12
spec:
  # ...
status:
  observedGeneration: 12
  conditions:
    - type: ResolvedRefs
      status: True
      observedGeneration: 12
----
where:

* The `status.observedGeneration` in the status matches the `metadata.generation`, indicating that the status is up-to-date for the latest `spec`.
* The `conditions` array reports any issues with the resource.
** `ResolvedRefs` is the condition type used to report any issues with referenced resources.
** `status` value of the condition. If `True`, all references resources resolve correctly. `False` indicates there are issues.

A status value of `False` means that the `KafkaProxy` resource is missing. In this case, the condition includes `reason` and `message` properties with more details.