// file included in the following:
//
// kroxylicious-operator/assemblies/assembly-operator-deploy-a-proxy.adoc

[id='con-virtualkafkacluster-overview-{context}']
= Virtual cluster configuration

[role="_abstract"]
A `VirtualKafkaCluster` resource defines a logical Kafka cluster that is accessible to clients over the network.

The virtual cluster references the following resources, which must be in the same namespace:

* A `KafkaProxy` resource that the proxy is part of.
* One or more `KafkaProxyIngress` resources that expose the virtual cluster to Kafka clients and provide virtual-cluster-specific configuration to the ingress (such as TLS certificates and other parameters).
* A `KafkaService` resource that defines the backend Kafka cluster.
* Zero or more `KafkaProtocolFilter` resources that apply filters to the Kafka protocol traffic passing between clients and the backend Kafka cluster.

This example shows a `VirtualKafkaCluster`, exposing it to Kafka clients running on the same Kubernetes cluster.
It uses plain TCP (as opposed to TLS) as the transport protocol.

.Example `VirtualKafkaCluster` configuration with single `clusterIP` ingress
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef: # <1>
    name: simple
  targetKafkaServiceRef: # <2>
    name: my-cluster
  ingresses:
    - ingressRef: # <3>
        name: cluster-ip
----
<1> Identifies the `KafkaProxy` resource that this virtual cluster is part of.
<2> The `KafkaService` that defines the Kafka cluster proxied by the virtual cluster.
<3> Ingresses that expose the virtual cluster.
  Each ingress references a `KafkaProxyIngress` by name.

This example shows a `VirtualKafkaCluster`, exposing it to Kafka clients running both on and off-cluster, both using TLS.
Because TLS is used, the ingress configuration must reference a TLS server certificate.

.Example `VirtualKafkaCluster` configuration with two ingresses using TLS
[source,yaml]
----
kind: VirtualKafkaCluster
apiVersion: kroxylicious.io/v1alpha1
metadata:
  name: my-cluster
  namespace: my-proxy
spec:
  proxyRef:
    name: simple
  targetKafkaServiceRef:
    name: my-cluster
  ingresses:
    - ingressRef:
        name: cluster-ip
        certificateRef:
          name: 'cluster-ip-server-cert' # <1>
          kind: Secret
    - ingressRef:
        name: load-balancer
        certificateRef:
          name: 'external-server-cert' # <2>
          kind: Secret
----
<1> Reference to a secret containing the server certificate for the `clusterIP` ingress.
<2> Reference to a secret containing the server certificate for the `loadBalancer` ingress.

include::./con-virtualkafkacluster-clusterip-generate-tls-certificates.adoc[leveloffset=+1]
include::./con-virtualkafkacluster-loadbalancer-generate-tls-certificates.adoc[leveloffset=+1]
include::./proc-virtualkafkacluster-loadbalancer-dns-config.adoc[leveloffset=+1]
