////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

[id='con-configuring-vc-target-{context}']
= Configuring a target cluster

[role="_abstract"]
A cluster definition describes the physical upstream Kafka cluster. The `my-cluster-proxy` virtual cluster
proxies that cluster by naming it in `target.cluster`.

The cluster definition defines two properties:

1. `bootstrapServers`: Comma-separated list of bootstrap addresses for the Kafka cluster being proxied.   If the cluster exposes a bootstrap endpoint (as is the case with some cloud-based Kafka services or clusters managed by Strimzi), use that address.  If the cluster does not have a specific bootstrap endpoint (as is the case with a standard Kafka deployment) list the address of several broker nodes. This helps spread the bootstrapping load and improves reliability.

2. `tls`: TLS configuration for connecting to the target Kafka cluster.
See xref:con-configuring-vc-target-tls-{context}[Securing connections to target clusters] for more details.

When multiple bootstrap servers are configured, the bootstrap server is selected using the `round-robin` strategy.

.Example using default strategy
[source,yaml]
----
#...
clusterDefinitions:
  - name: my-cluster
    bootstrapServers: my-cluster-kafka-bootstrap-0.kafka.svc.cluster.local:9093,my-cluster-kafka-bootstrap-1.kafka.svc.cluster.local:9093,my-cluster-kafka-bootstrap-2.kafka.svc.cluster.local:9093
    tls: {}
virtualClusters:
    - name: my-cluster-proxy
      # ...
      target:
        cluster: my-cluster
#...
----

`bootstrapServerSelection.strategy` is still configured on the deprecated `targetCluster` form. It is not accepted on `clusterDefinitions`.
The bootstrapping process selects one bootstrap server from the list of configured servers.
The following strategies are supported:

* `round-robin`: This strategy selects a server from the configured list of servers in a round-robin manner starting from the first server, looping back after the last server is selected. This is the default strategy used when no strategy is explicitly configured.
* `random`: This strategy selects a random server from the configured list of servers.

.Example configuring a bootstrap server selection strategy
[source,yaml]
----
#...
virtualClusters:
  - name: my-cluster-proxy
    #...
    targetCluster:
      bootstrapServers: my-cluster-kafka-bootstrap-0.kafka.svc.cluster.local:9093,my-cluster-kafka-bootstrap-1.kafka.svc.cluster.local:9093,my-cluster-kafka-bootstrap-2.kafka.svc.cluster.local:9093
      bootstrapServerSelection:
        strategy: "round-robin"
      tls: {}
#...
----
where:

* `strategy` specifies the strategy for bootstrap server selection.
