////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// kroxylicious-operator/_assemblies/assembly-operator-deploy-a-proxy.adoc

[id='con-kafkaservice-by-bootstrap-{context}']
= Configuration for proxied Kafka clusters

[role="_abstract"]
A proxied Kafka cluster is configured in a `KafkaService` resource, which specifies how the proxy connects to the cluster.
The Kafka cluster may or may not be running in the same Kubernetes cluster as the proxy: Network connectivity is all that's required.

This example shows a `KafkaService` defining how to connect to a Kafka cluster at `kafka.example.com`.

.Example `KafkaService` configuration
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  nodeIdRanges:
    - name: brokers
      start: 0
      end: 5
  # ...
----
where:

* `bootstrapServers` specifies a comma-separated list of addresses in `<host>:<port>` format. Including multiple broker addresses helps clients connect when one is unavailable.
* `nodeIdRanges` declares the IDs of all the broker nodes in the Kafka cluster
* `name` is optional, but specifying it can make errors easier to diagnose.
* `start` defines the start of the ID range, inclusive.
* `end` defines the end of the ID range, inclusive.

