////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// kroxylicious-operator/_assemblies/assembly-operator-secure-proxy-broker-connection.adoc

[id='con-configuring-kafkaservice-trust-{context}']
= TLS trust configuration for proxy-to-cluster connections

[role="_abstract"]
By default, the proxy uses the platform's default trust store when connecting to the proxied cluster over TLS.  
This works if the cluster's TLS certificates are signed by a well-known public Certificate Authority (CA), but fails if they’re signed by a private CA instead.

IMPORTANT: It is good practice to configure trust explicitly, even when proxied cluster's TLS certificates are signed by a public CA.

This example configures a `KafkaService` to trust TLS certificates signed by any Certificate Authority (CA) listed in the `trusted-cas.pem` entry of the `ConfigMap` named `trusted-cas`.

.Example `KafkaService` configuration for trusting certificates provided by a `ConfigMap`
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    trustAnchorRef:
      name: trusted-cas
      kind: ConfigMap
      key: trusted-cas.pem
    # ...
----
where:
* `trustAnchorRef`  references a separate Kubernetes resource which contains the CA certificates to be trusted
* `name` is the name of the `ConfigMap` providing the CA certificates. This resource must exist in the same namespace as the `KafkaService`
* `kind` is optional and defaults to `ConfigMap`.
* `key` The `key` identifies the entry in the given resource. The corresponding value must be a PEM-encoded set of CA certificates.

.Example `KafkaService` configuration for trusting certificates provided by a `Secret`
[source,yaml]
----
kind: KafkaService
metadata:
  # ...
spec:
  bootstrapServers: kafka.example.com:9092
  tls:
    trustAnchorRef:
      kind: Secret
      name: trusted-cas
      key: trusted-cas.pem
    # ...
----
* `name` is the name of the Secret providing the CA certificates. This resource must exist in the same namespace as the `KafkaService`
* `kind` is must be `Secret`.
* `key` The `key` identifies the entry in the given resource. The corresponding value must be a PEM-encoded set of CA certificates.