// file included in the following:
//
// con-virtualkafkafkacluster-overview.adoc

[id='con-virtualkafkacluster-loadbalancer-generate-tls-certificates-{context}']

= Generating TLS certificates for `loadBalancer` ingress type

[role="_abstract"]

When using `loadBalancer` ingress type, you must provide suitable TLS certificates to secure communication.

The basic steps are as follows:

* Generate a TLS server certificate that covers the bootstrap and broker names assigned to the virtual cluster by the ingress.
* Provide the certificate to the virtual cluster using a Kubernetes `Secret` of type `kubernetes.io/tls`.

The exact procedure for generating the certificate depends on the tooling and processes used by your organization.

The certificate must meet the following criteria:

* The certificate needs to be signed by a CA that is trusted by the *off-cluster applications* that connect to the virtual cluster.
* The format of the certificate must be PKCS#8 encoded PEM (Privacy Enhanced Mail).
  It must not be password protected.
* The certificate must use SANs (Subject Alternate Names) to list the bootstrap and all the broker names or use a wildcard TLS certificate that covers them all.
Assuming a `bootstrapAddress` of `$(virtualClusterName).kafkaproxy.example.com`, an `advertisedBrokerAddressPattern` of `broker-$(nodeId).$(virtualClusterName).kafkaproxy.example.com`, a Kafka cluster using node IDs (0-2), and a virtual cluster name of `my-cluster`, the following SANs must be listed in the certificate:
+
[source,text]
----
mycluster.kafkaproxy.example.com
broker-0.mycluster.kafkaproxy.example.com
broker-1.mycluster.kafkaproxy.example.com
broker-2.mycluster.kafkaproxy.example.com
----

include::../../_snippets/snip-create-secret-containing-pem-certificate.adoc[]

