// file included in the following:
//
// kroxylicious-operator/_assemblies/assembly-operator-secure-filter.adoc

= Security-sensitive values in filter resources

[role="_abstract"]
Filter resources can be configured to handle security-sensitive values like passwords or keys by referencing Kubernetes `Secret` and `ConfigMap` resources. 

== Template use and value interpolation

Interpolation is supported in `spec.configTemplate` for the automatic substitution of placeholder values at runtime. 
This allows security-sensitive values, such as passwords or keys, to be specified in Kubernetes `Secret` resources rather than directly in the `KafkaProtocolFilter` resource.
Likewise, things like trusted CA certificates can be defined in `ConfigMap` resources.

The operator determines which `Secret` and `ConfigMap` resources are referenced by a `KafkaProtocolFilter` resource and declares them as `volumes` in the proxy `Pod`, mounted into the proxy container.
This example shows how to configure the `RecordEncryptionFilter` using a Vault KMS deployed in the same Kubernetes cluster.

.Example `KafkaProtocolFilter` configuration
[source,yaml]
----
kind: KafkaProtocolFilter
metadata:
  # ...
spec:
  type: RecordEncryption # <1>
  configTemplate: # <2>
    kms: VaultKmsService
    kmsConfig:
      vaultTransitEngineUrl: http://vault.vault.svc.cluster.local:8200/v1/transit
      vaultToken:
        password: ${secret:vault:token} # <3>
    selector: TemplateKekSelector
    selectorConfig:
      template: "$(topicName)" # <4>
----
<1> The `type` is the Java class name of the proxy filter. If the unqualified name is ambiguous, it must be qualified by the filter package name.
<2> The `KafkaProtocolFilter` requires a `configTemplate`, which supports _interpolation references_.
<3> The `password` uses an _interpolation reference_, enclosed by `${` and `}` instead of a literal value. The operator supplies the value at runtime from the specified `Secret`.
<4>  The selector `template` is interpreted by the proxy. It uses different delimiters, `$(` and `)`, than the _interpolation reference_.

== Structure of interpolation references

Let's look at the example interpolation reference `${secret:vault:token}` in more detail.

It starts with `${` and ends with `}`. Between these, it is broken into three parts, separated by colons (`:`):

* `secret` is a _provider_. Supported providers are `secret` and `configmap` (note the use of lower case).
* `vault` is a _path_. The interpretation of the path depends on the provider.
* `token` is a _key_. The interpretation of the key also depends on the provider.

For both `secret` and `configmap` providers:

* The path is interpreted as the name of a `Secret` or `ConfigMap` resource in the same namespace as the `KafkaProtocolFilter` resource.
* The key is interpreted as a key in the `data` property of the `Secret` or `ConfigMap` resource.