:_mod-docs-content-type: CONCEPT

[id='con-configuring-vc-transport-subject-builders-{context}']
= Configuring the transport subject builder

[role="_abstract"]

Some filters need to know the verified identity of the client, derived from its successful authentication.
This is called the authenticated subject.

For applications using TLS client authentication, the virtual cluster can build the authenticated subject from information within TLS client certificate presented by application to the proxy.

The transport subject builder can be configured to control how the information is turned into principals within the authenticated subject.
For instance, it is possible build a principal from parts of the X500 Principal.
A typical use-case might be mapping a distinguished name such as `CN=myapp,OU=dev,O=kroxylicious.io,C=US` into `myapp`.

NOTE: For applications using SASL authentication, see {SASLInspectionGuide} for a way to build the authenticated subject from a successful client/broker SASL authentication.

== Configuration

The configuration for the transport subject builder looks like this:

.Example transport subject builder configuration

[source,yaml]
----
# ...
virtualClusters:
  - name: my-cluster-proxy
    # ...
    subjectBuilder:
      type: DefaultTransportSubjectBuilderService
      config:
        addPrincipals:
          - from: <field name>
            map:
              - replaceMatch: <match replace flags 1>
              - ...
              - replaceMatch: <match replace flags n>
              - else: identity|anonymous
            principalFactory: <principal factory factory>
        # - from: ...
----
include::../../_snippets/snip-subject-builder-common-params.adoc[]

== Supported fields

|===
|Field name|Description

|clientTlsSubject
|X500 Principal

|clientTlsSanRfc822Name
|Email address from the Subject Alternate Names

|clientTlsSanDirName
|DirName from the Subject Alternate Names

|clientTlsSanDnsName
|DNSName from the Subject Alternate Names

|clientTlsSanUri
|URI from the Subject Alternate Names
|===

include::../../_snippets/snip-subject-builder-replacement-matchers.adoc[]

