#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
kind: Filter
apiVersion: filter.kroxylicious.io/v1alpha1
metadata:
  name: validation
  namespace: my-proxy
spec:
  type: io.kroxylicious.proxy.filter.validation.RecordValidation
  config:
    # ...