// Module included in the following assemblies:
//
// assemblies/assembly-operator-install.adoc

[id='install-cluster-operator-{context}']
= Installing the Kroxylicious Operator

[role="_abstract"]
This procedure shows how to install the Kroxylicious Operator in your Kubernetes cluster.

.Prerequisites

* You need an account with permission to create and manage `CustomResourceDefinition` and RBAC (`ClusterRole`) resources.
* You have downloaded the xref:downloads-{context}[release artifacts] and extracted the contents into the current directory.

.Procedure

. Edit the Kroxylicious installation files to use the namespace the operator is going to be installed into.
+
For example, in this procedure the operator is installed into the namespace `my-kroxylicious-operator-namespace`.
+
include::../../snippets/snip-operator-namespace-sed.adoc[]

. Deploy the Kroxylicious operator:
+
[source,shell,subs="+quotes,attributes+"]
kubectl create -f install

. Check the status of the deployment:
+
[source,shell,subs="+quotes"]
----
kubectl get deployments -n my-kroxylicious-operator-namespace
----
+
.Output shows the deployment name and readiness
[source,shell,subs="+quotes"]
----
NAME                      READY  UP-TO-DATE  AVAILABLE
kroxylicious-operator     1/1    1           1
----
+
`READY` shows the number of replicas that are ready/expected.
The deployment is successful when the `AVAILABLE` output shows `1`.
