#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    filterDefinitions:
    - name: multi-tenant
      type: MultiTenantTransformationFilterFactory
    defaultFilters:
      - multi-tenant
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      devenv1:
        targetCluster:
          bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        clusterNetworkAddressConfigProvider:
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: minikube:30192
        logNetwork: false
        logFrames: false
      devenv2:
        targetCluster:
          bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        clusterNetworkAddressConfigProvider:
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: minikube:30292
        logNetwork: false
        logFrames: false
