////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-record-validation-filter.adoc

[id='con-example-kafkaprotocolfilter-resource-{context}']
= Example `KafkaProtocolFilter` resource

[role="_abstract"]
If your instance of Kroxylicious runs on Kubernetes, you must use a `KafkaProtocolFilter` resource to contain the filter configuration.

Here's a complete example of a `KafkaProtocolFilter` resource configured for record validation:

.Example `KafkaProtocolFilter` resource for record validation
[source,yaml]
----
kind: KafkaProtocolFilter
metadata:
  name: my-validation-filter
spec:
  type: RecordValidation
  configTemplate:
    rules:
    - topicNames:
        - <topic name>
      keyRule:
        <rule definition>
      valueRule:
        <rule definition>
    defaultRule:
      keyRule:
        <rule definition>
      valueRule:
        <rule definition>
----
where:

* `topicNames` provides the list of  topic names to which the validation rules will be applied.
* `keyRule` provides the validation rules that are applied to the record's key.
* `valueRule` provides the validation rules that are applied to the record's value.
* `defaultRule` provides the defaults that is applied to any topics for which there is no explicit rule defined.

Refer to the {OperatorGuide} for more information about configuration on Kubernetes.
