:_mod-docs-content-type: CONCEPT

// file included in the following:
//
// assembly-configuring-record-validation-filter.adoc

[id='con-example-proxy-config-{context}']
= Example proxy configuration file

[role="_abstract"]
If your instance of the Kroxylicious Proxy runs directly on an operating system, provide the filter configuration in the `filterDefinitions` list of your proxy configuration.
Here's a complete example of a `filterDefinitions` entry configured for record validation:

// .Example `filterDefinitions` configuration {foo}
[source,yaml]
----
filterDefinitions:
  - name: my-record-validation
    type: RecordValidation
    config:
        rules:
        - topicNames:                                                  # <1>
            - <topic name>
          keyRule:
            <rule definition>                                          # <2>
          valueRule:
            <rule definition>                                          # <3>
        defaultRule:                                                   # <4>
          keyRule:
            <rule definition>                                          # <2>
          valueRule:
            <rule definition>                                          # <3>
----
<1> List of topic names to which the validation rules will be applied.
<2> Validation rules that are applied to the record's key.
<3> Validation rules that are applied to the record's value.
<4> (Optional) Default rule that is applied to any topics for which there is no explict rule defined.

Refer to the {ProxyGuide} for more information about configuring the proxy.
