////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: PROCEDURE


// file included in the following:
//
// assembly-proxy-monitoring.adoc

[id='proc-proxy-setting-log-levels-{context}']
= Setting log levels

[role="_abstract"]

The Kroxylicious {github-release}[binary distribution^] includes https://logging.apache.org/log4j/2.x[log4j2] as the default logging backend.

When using the `bin/kroxylicious-start.sh` script from the binary distribution, you can set an environment variable to load a custom `log4j2` configuration file or change the root logging level.

.Environment variable to load a custom `log4j2` file
[source,properties]
----
KROXYLICIOUS_LOGGING_OPTIONS="-Dlog4j2.configurationFile=/path/to/custom/log4j2.yaml"
----

.Environment variable to change the root logging level
[source,properties]
----
KROXYLICIOUS_ROOT_LOG_LEVEL="DEBUG"
----

NOTE: Setting the root log level to `DEBUG` or `TRACE` will produce very verbose logs.

[id='proc-proxy-json-log-format-{context}']
== Switching to JSON log format

By default, Kroxylicious outputs logs in human-readable text format. You can switch to structured JSON output for integration with log aggregation systems.

.Procedure

. Set the `KROXYLICIOUS_LOG_FORMAT` environment variable:
+
[source,bash]
----
export KROXYLICIOUS_LOG_FORMAT=json
----

. Start Kroxylicious:
+
[source,bash]
----
bin/kroxylicious-start.sh
----

.Expected output (JSON format)

[source,json]
----
{
  "@version": "1",
  "@timestamp": "2026-04-01T14:25:30.123Z",
  "message": "Connection established",
  "logger_name": "io.kroxylicious.proxy.internal.FilterHandler",
  "thread_name": "kafka-request-handler-1",
  "level": "INFO",
  "level_value": 20000,
  "stack_trace": null,
  "sessionId": "abc-123",
  "clientId": "producer-1"
}
----

NOTE: MDC (Mapped Diagnostic Context) fields like `sessionId` and `clientId` appear as top-level fields in JSON output.

.Switching back to text format

Remove the environment variable or set it to `text`:

[source,bash]
----
unset KROXYLICIOUS_LOG_FORMAT
# or
export KROXYLICIOUS_LOG_FORMAT=text
----
