////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: PROCEDURE


// file included in the following:
//
// assembly-proxy-monitoring.adoc

[id='proc-proxy-setting-log-levels-{context}']
= Setting log levels

[role="_abstract"]

The Kroxylicious {github-release}[binary distribution^] includes https://logging.apache.org/log4j/2.x[log4j2] as the default logging backend.

When you use the `bin/kroxylicious-start.sh` script from the binary distribution, you can configure logging behavior using the following environment variables.

.Logging environment variables
[cols="2,1,2,3",options="header"]
|===
|Environment variable |Default |Valid values |Description

|`KROXYLICIOUS_ROOT_LOG_LEVEL`
|`WARN`
|`TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`, `OFF`
|Log level for all loggers that are not otherwise configured.

|`KROXYLICIOUS_APP_LOG_LEVEL`
|`INFO`
|`TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `FATAL`, `OFF`
|Log level for Kroxylicious loggers (`io.kroxylicious.*`). This setting takes precedence over `KROXYLICIOUS_ROOT_LOG_LEVEL` for application code.

|`KROXYLICIOUS_LOG_FORMAT`
|`text`
|`text`, `json`
|Output format for log messages. Set to `json` to enable structured JSON output.

|`KROXYLICIOUS_LOG_JSON_TEMPLATE`
|`classpath:LogstashJsonEventLayoutV1.json`
|Any valid https://logging.apache.org/log4j/2.x/manual/json-template-layout.html[Log4j2 JsonTemplateLayout] event template URI.
|JSON layout template used when `KROXYLICIOUS_LOG_FORMAT=json`. For example, use `classpath:EcsLayout.json` for Elastic Common Schema or `classpath:GelfLayout.json` for GELF format.

|`KROXYLICIOUS_LOGGING_OPTIONS`
|(built-in defaults)
|Any valid log4j2 JVM system properties.
|Overrides the entire set of log4j2 JVM system properties. When set, the default `-Dlog4j2.configurationFile` and `-Dlog4j2.contextSelector` options are replaced. You must include all required options explicitly.
|===

The following examples show how to set the application log level and configure a custom Log4j2 configuration.

.Setting the application log level to DEBUG
[source,properties]
----
KROXYLICIOUS_APP_LOG_LEVEL="DEBUG"
----

NOTE: Setting the log level to `DEBUG` or `TRACE` produces very verbose logs.

.Loading a custom log4j2 configuration file
[source,bash]
----
export KROXYLICIOUS_LOGGING_OPTIONS="-Dlog4j2.configurationFile=/path/to/custom/log4j2.yaml \
  -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector"
----

WARNING: Setting `KROXYLICIOUS_LOGGING_OPTIONS` replaces the built-in defaults.
Always include `-Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector` to preserve asynchronous logging.

[id='proc-proxy-json-log-format-{context}']
== Switching to JSON log format

By default, Kroxylicious outputs logs in human-readable text format.
You can switch to structured JSON output to integrate with log aggregation systems such as the Elastic Stack (ELK) or Splunk.

The JSON format uses https://logging.apache.org/log4j/2.x/manual/json-template-layout.html[Log4j2's JsonTemplateLayout] with the Logstash JSON Event V1 format.
Structured context fields emitted by Kroxylicious appear as top-level fields alongside standard log metadata.

.Procedure

. Set the `KROXYLICIOUS_LOG_FORMAT` environment variable before starting the proxy:
+
[source,bash]
----
export KROXYLICIOUS_LOG_FORMAT=json
bin/kroxylicious-start.sh
----


Example JSON log output:

[source,json]
----
{
  "@version": "1",
  "@timestamp": "2026-04-01T14:25:30.123Z",
  "message": "Connection established",
  "logger_name": "io.kroxylicious.proxy.internal.FilterHandler",
  "thread_name": "kafka-request-handler-1",
  "level": "INFO",
  "level_value": 20000,
  "sessionId": "abc-123",
  "clientId": "producer-1",
  "apiKey": "Produce"
}
----


When an exception is logged, a `stack_trace` field is included in the output.

. To switch back to text format, remove the environment variable or set it to `text`:


[source,bash]
----
unset KROXYLICIOUS_LOG_FORMAT
# or
export KROXYLICIOUS_LOG_FORMAT=text
----
