// This glossary is shared by both proxy and operator.
// For terms that are applicable to only one guide, use ifeval conditionals.
// Don't define terms specific to the domain of filters here, use a filter guide specific
// glossary instead.

:_mod-docs-content-type: REFERENCE

= Glossary

[role="_abstract"]
Glossary of terms used in the Kroxylicious documentation.

API:: Application Programmer Interface.
CA:: Certificate Authority. An organization that issues certificates.
ifeval::["{guide}" == "operator"]
CR:: Custom Resource. An instance resource of a CRD. In other words, a resource of a kind that is not built into Kubernetes.
CRD:: Custom Resource Definition. A Kubernetes API for defining Kubernetes API extensions.
endif::[]
mTLS:: Mutual Transport Layer Security. A configuration of TLS where the client presents a certificate to a server, which the server authenticates.
TLS:: The Transport Layer Security. A secure transport protocol where a server presents a certificate to a client, which the client authenticates. TLS was previously known as the Secure Sockets Layer (SSL).
TCP:: The Transmission Control Protocol.
