////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: CONCEPT

// Module included in the following:
//
// _assemblies/assembly-admission-webhook-install.adoc

[id='con-admission-webhook-release-artifacts-{context}']
= Admission webhook release artifacts

[role="_abstract"]
ifdef::IncludeSingleYamlFileManifest[]
Kroxylicious provides multiple distribution formats to suit different installation workflows. You can choose between archive distributions (zip or tar.gz) or single-file rendered YAML manifests.
endif::IncludeSingleYamlFileManifest[]

ifndef::IncludeSingleYamlFileManifest[]
Kroxylicious provides archive distributions (zip or tar.gz) containing the installation resources.
endif::IncludeSingleYamlFileManifest[]

== Archive distributions

Archive distributions are available in zip and tar.gz formats from {github-release-link}:

Zip archive:: link:{WebhookAssetZipLink}[{WebhookAssetZipFileName}] contains CRD definitions, installation files, examples, and documentation.

Tar.gz archive:: link:{WebhookAssetTgzLink}[{WebhookAssetTgzFileName}] is the same content as the zip archive, provided in tar.gz format for environments that prefer this format.

ifdef::IncludeSingleYamlFileManifest[]

== Single YAML file manifest

The single YAML file manifest and supplemental files are available from {github-release-link}:

Full install manifest:: link:{WebhookInstallManifestLink}[{WebhookInstallManifestFileName}] contains all required resources (CRD definitions and installation files).

CRDs-only manifest:: link:{WebhookCrdsManifestLink}[{WebhookCrdsManifestFileName}] contains only CRD definitions.

Examples archive:: link:{WebhookExamplesZipLink}[{WebhookExamplesZipFileName}] contains cert-manager configuration examples and other reference resources.
endif::IncludeSingleYamlFileManifest[]
