////
  // Copyright Kroxylicious Authors.
  //
  // Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
////

:_mod-docs-content-type: PROCEDURE

// Module included in the following:
//
// admission-webhook-guide/index.adoc

[id='proc-using-admission-webhook-{context}']
= Injecting a Kroxylicious sidecar into application pods

[role="_abstract"]
This procedure shows how to configure sidecar injection for a namespace and verify that the proxy sidecar is injected into application pods.

// TODO: Add a complete end-to-end example with a sample Kafka client application.
// TODO: Document configuring filters via filterDefinitions.
// TODO: Document configuring TLS to the target Kafka cluster via targetClusterTls.
// TODO: Document resource requests and limits configuration.
// TODO: Document third-party plugin image configuration.
// TODO: Document delegated annotations for application pod owner overrides.

.Prerequisites

* The admission webhook is xref:proc-install-admission-webhook-{context}[installed and running].
* A Kafka cluster is available and you know its bootstrap server address.

.Procedure

. Create a `KroxyliciousSidecarConfig` custom resource in the namespace where your application pods run.
At a minimum, you must specify the `targetBootstrapServers` field:
+
[source,yaml,subs="+quotes,attributes+"]
----
apiVersion: kroxylicious.io/v1alpha1
kind: KroxyliciousSidecarConfig
metadata:
  name: my-sidecar-config
  namespace: _my-app-namespace_
spec:
  targetBootstrapServers: _my-kafka-cluster-bootstrap:9092_
----
+
Apply the resource:
+
[source,shell,subs="+quotes"]
----
kubectl apply -f my-sidecar-config.yaml
----

. Label the namespace to enable sidecar injection:
+
[source,shell,subs="+quotes"]
----
kubectl label namespace _my-app-namespace_ kroxylicious.io/sidecar-injection=enabled
----

. Create or recreate application pods in the labelled namespace.
+
IMPORTANT: The webhook only processes pod `CREATE` requests. Existing pods are not modified. You must delete and recreate pods (or roll the deployment) for the sidecar to be injected.

. Verify that the sidecar was injected by listing the containers in a pod:
+
[source,shell,subs="+quotes"]
----
kubectl get pod _my-pod_ -n _my-app-namespace_ -o jsonpath='{.spec.containers[*].name}'
----
+
The output should include `kroxylicious-proxy` alongside your application containers.

. (Optional) To opt out individual pods from sidecar injection, set the following label on the pod:
+
[source,yaml,subs="+quotes"]
----
metadata:
  labels:
    kroxylicious.io/inject-sidecar: "false"
----
