#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements. See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
name: System Tests for Pull-Requests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**/**.md'
      - '**/**.txt'
      - '.github/**'
      - '!.github/workflows/system-tests-pr.yaml'
      - '!.github/workflows/run-system-tests.yaml'
      - '!.github/workflows/build-kroxylicious-container-images.yaml'
      - '!.github/actions/**'
      - 'kroxylicious-docs**/**'
      - 'kroxylicious-integration-test**/**'
      - 'kroxylicious-*benchmarks/**'
    branches:
      - "main"
      - 'release/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_images:
    uses: ./.github/workflows/build-kroxylicious-container-images.yaml

  set_variables:
    runs-on: ubuntu-latest
    outputs:
      kafka_client: ${{ steps.kafkaClient.outputs.kafka_client }}
      fortanix: ${{ steps.fortanixKMS.outputs.fortanix }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: 'Discover test clients'
        working-directory: kroxylicious-systemtests
        id: discover
        run: |
          # WARNING: possible coupling between java class and shell script
          client_types=$(grep -oE '^\s+[A-Z][A-Z0-9_]+' ./src/main/java/io/kroxylicious/systemtests/enums/KafkaClientType.java \
            | tr -d ' ' \
            | tr '[:upper:]' '[:lower:]' \
            | paste -sd ',')
          TEST_CLIENTS="[$(echo "$client_types" | sed 's/[^,]*/"&"/g')]"
          echo "test_clients=$TEST_CLIENTS" >> $GITHUB_OUTPUT
      - name: 'Get PR labels'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_LABELS=[$(echo $(gh api --jq '.labels.[].name' /repos/{owner}/{repo}/pulls/${{ github.event.pull_request.number }}) | sed 's/ /,/g')]
          echo "LABELS=$PR_LABELS" >> "$GITHUB_ENV"
      - name: 'Set kafka client'
        id: kafkaClient
        run: |
          KAFKA_CLIENTS="${{ steps.discover.outputs.test_clients }}"
          PR_LABELS="${{ env.LABELS }}"
          KAFKA_CLIENT=$(echo "${PR_LABELS[@]},${KAFKA_CLIENTS[@]}" | sed 's/,/\n/g; s/\[//g; s/\]//g; s/test\/system-test\///g' | sort | uniq -d)
          KAFKA_CLIENT=$([[ -z $KAFKA_CLIENT ]] && echo 'strimzi_test_client' || echo $KAFKA_CLIENT)
          echo "kafka_client=$KAFKA_CLIENT" >> "$GITHUB_OUTPUT"
          echo "$KAFKA_CLIENT"
      - name: 'Set Fortanix KMS'
        id: fortanixKMS
        run: |
          PR_LABELS="${{ env.LABELS }}"
          FORTANIX=$([[ ${PR_LABELS[*]} =~ 'fortanix' ]] && echo 'true' || echo 'false')
          echo "fortanix=$FORTANIX" >> "$GITHUB_OUTPUT"
          echo "$FORTANIX"

  run_system_tests:
    needs: [build_images,set_variables]
    uses: ./.github/workflows/run-system-tests.yaml
    with:
      kafkaClient: ${{ needs.set_variables.outputs.kafka_client }}
      testFortanixKMS: ${{ needs.set_variables.outputs.fortanix }}
