title: "feat(kms-vault): introduce vaultUrl and credentials object, deprecating legacy options"
type: added
merge_requests:
  - 4980
important_notes:
  - "Deprecation: Top-level `vaultTransitEngineUrl`, `vaultToken`, and `vaultTokenPassword` in HashiCorp Vault KMS configuration are deprecated in favor of `vaultUrl` and the new `credentials` object."

