title: "feat(kms-vault): introduce credentials object and deprecate legacy token options"
type: added
merge_requests:
  - 4980
important_notes:
  - "Deprecation: Top-level `vaultToken` and `vaultTokenPassword` in HashiCorp Vault KMS configuration are deprecated in favor of the new `credentials` object."
